// database/certifTrackRainforest.js
// Session 8d — Rainforest Alliance complet
// 137 exigences supplémentaires (en plus des 3 démo Session 8)
// Total après seed : 140 exigences Rainforest Alliance
//
// Sources de référence :
//   - Rainforest Alliance Sustainable Agriculture Standard 2020, version 1.3 (2024)
//     - Farm Requirements (production)
//     - Supply Chain Requirements (transformation/négoce)
//   - Standard adopté à 100% par les ex-UTZ depuis fusion 2018
//   - Annexes : RACP (Certification Platform), MultiSite Standard
//
// Périmètre : production propre + filière collecte (groupe de petits producteurs)
//
// Triple pilier RA : conservation biodiversité + conditions de travail décentes
//                  + viabilité économique
//
// ⚠️ Validation finale par auditeur RA (NSF International, IMO, Africert) avant audit réel.

import * as SQLite from 'expo-sqlite';

const db = SQLite.openDatabaseSync('agrisuite.db');

const REF_CODE = 'RAINFOREST';

// ============================================================
// CATALOGUE EXIGENCES RAINFOREST ALLIANCE — 137 entrées
// ============================================================

const EXIGENCES_RA = [

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 1 — GESTION (15 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-MGT-01',
    cat: 'gouvernance',
    titre: 'Système de gestion documenté et opérationnel',
    desc: 'Système de gestion écrit définissant : politique de durabilité, structure organisationnelle, responsabilités, procédures clés. Validé par direction.',
    crit: 'majeure',
    preuve: 'Manuel système de gestion daté, signé.',
    ref: 'RA Standard 2020 v1.3, Chapitre 1 §1.1.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-02',
    cat: 'gouvernance',
    titre: 'Coordinateur RA désigné formellement',
    desc: 'Personne formellement désignée responsable de la conformité RA, formée au standard, point de contact pour l\'auditeur RA.',
    crit: 'majeure',
    preuve: 'Lettre de mission + CV + attestation formation RA.',
    ref: 'RA Standard 2020 v1.3, §1.1.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-03',
    cat: 'gouvernance',
    titre: 'Plan de gestion durable triennal',
    desc: 'Plan de gestion sur 3 ans incluant : objectifs annuels, ressources allouées, indicateurs de suivi pour chaque chapitre du standard.',
    crit: 'majeure',
    preuve: 'Document plan de gestion 3 ans signé.',
    ref: 'RA Standard 2020 v1.3, §1.1.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-04',
    cat: 'gouvernance',
    titre: 'Évaluation des risques annuelle',
    desc: 'Évaluation annuelle des risques sociaux, environnementaux, économiques sur l\'exploitation et la chaîne. Plan d\'atténuation associé.',
    crit: 'majeure',
    preuve: 'Document évaluation risques < 12 mois + plan atténuation.',
    ref: 'RA Standard 2020 v1.3, §1.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-05',
    cat: 'gouvernance',
    titre: 'Plan d\'amélioration continue (Continuous Improvement)',
    desc: 'Plan annuel avec objectifs SMART par thématique RA. Suivi trimestriel. Présenté en revue de direction.',
    crit: 'majeure',
    preuve: 'Plan amélioration + revues trimestrielles documentées.',
    ref: 'RA Standard 2020 v1.3, §1.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-06',
    cat: 'gouvernance',
    titre: 'Investissement minimum 2% revenus dans amélioration',
    desc: 'Pour groupe certifié : investissement minimum 2% des revenus de la certification dans actions d\'amélioration durabilité (formations, équipements, projets).',
    crit: 'majeure',
    preuve: 'Comptabilité analytique montrant investissements amélioration.',
    ref: 'RA Standard 2020 v1.3, §1.3.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-07',
    cat: 'gouvernance',
    titre: 'Politique de durabilité publique',
    desc: 'Politique de durabilité affichée publiquement : engagements environnementaux, sociaux, économiques. Signée par direction.',
    crit: 'majeure',
    preuve: 'Document politique + affichage + publication site web si existant.',
    ref: 'RA Standard 2020 v1.3, §1.1.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-08',
    cat: 'gouvernance',
    titre: 'Comité de sustainability constitué',
    desc: 'Comité interne dédié au suivi durabilité : représentants direction, production, RH, environnement. Réunions mensuelles minimum.',
    crit: 'mineure',
    preuve: 'Composition comité + PV réunions.',
    ref: 'RA Standard 2020 v1.3, §1.1.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-09',
    cat: 'gouvernance',
    titre: 'Procédure de gestion des plaintes',
    desc: 'Procédure permettant à toute partie prenante (employés, communautés, fournisseurs) de déposer plainte. Traitement, suivi, retour. Confidentialité.',
    crit: 'majeure',
    preuve: 'Procédure plaintes + registre des plaintes (anonymisé) + boîte plaintes.',
    ref: 'RA Standard 2020 v1.3, §1.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-10',
    cat: 'gouvernance',
    titre: 'Engagement communautés locales',
    desc: 'Identification et dialogue avec communautés voisines impactées. Consultations annuelles. Procédures FPIC (consentement libre, préalable et éclairé) pour expansion.',
    crit: 'majeure',
    preuve: 'Liste communautés identifiées + PV consultations.',
    ref: 'RA Standard 2020 v1.3, §1.5 + UN FPIC',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-11',
    cat: 'gouvernance',
    titre: 'Politique anti-corruption',
    desc: 'Charte anti-corruption signée. Formation annuelle des dirigeants. Signalement protégé. Sanctions définies.',
    crit: 'majeure',
    preuve: 'Charte + registre formations + procédure signalement.',
    ref: 'RA Standard 2020 v1.3, §1.1.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-12',
    cat: 'gouvernance',
    titre: 'Audit interne RA annuel',
    desc: 'Audit interne complet annuel par auditeur qualifié. Rapport, écarts, plan d\'actions. Précède audit externe RA.',
    crit: 'majeure',
    preuve: 'Rapport audit interne < 12 mois.',
    ref: 'RA Standard 2020 v1.3, §1.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-13',
    cat: 'gouvernance',
    titre: 'Revue de direction trimestrielle',
    desc: 'Réunion trimestrielle direction : revue indicateurs, alertes, actions correctives, allocation ressources. PV signé.',
    crit: 'mineure',
    preuve: 'PV revues direction.',
    ref: 'RA Standard 2020 v1.3, §1.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-14',
    cat: 'gouvernance',
    titre: 'Plan de gestion de groupe (si SCI)',
    desc: 'Si certification de groupe (filière collecte) : plan SCI documenté avec cartographie producteurs, calendrier inspections, grilles, sanctions.',
    crit: 'majeure',
    preuve: 'Plan SCI complet (alignement avec Session 9 AgriSuite).',
    ref: 'RA Standard 2020 v1.3 Multi-site',
    auto: 0, regle: null,
  },
  {
    code: 'RA-MGT-15',
    cat: 'gouvernance',
    titre: 'Toutes exigences majeures justifiées par preuve',
    desc: 'Pour chaque exigence majeure RA, au moins une preuve enregistrée dans CertifTrack.',
    crit: 'majeure',
    preuve: 'Vérification automatique par moteur de conformité.',
    ref: 'RA Standard 2020 v1.3, §1.6',
    auto: 1, regle: 'PREUVE_MANQUANTE_MAJEURE',
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 2 — TRAÇABILITÉ (12 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-TRAC-02',
    cat: 'tracabilite',
    titre: 'Plateforme RACP enregistrée et utilisée',
    desc: 'Compte actif sur Rainforest Alliance Certification Platform (RACP). Toutes transactions RA déclarées sur la plateforme dans les délais.',
    crit: 'majeure',
    preuve: 'Captures écran RACP + identifiants compte + dernières transactions.',
    ref: 'RA Standard 2020 v1.3, Chapitre 2 §2.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-03',
    cat: 'tracabilite',
    titre: 'Numéro de licence RA pour usage logo',
    desc: 'Si logo RA grenouille verte utilisé : licence RA Mark obtenue. Conformité aux règles graphiques (taille minimale, couleurs).',
    crit: 'majeure',
    preuve: 'Contrat licence Rainforest Alliance Mark.',
    ref: 'RA Trademark Use Guidelines',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-04',
    cat: 'tracabilite',
    titre: 'Volumes RA déclarés trimestriellement',
    desc: 'Reporting trimestriel sur RACP : volumes produits, vendus, en stock. Rapprochement avec comptabilité.',
    crit: 'majeure',
    preuve: 'Captures écran RACP + extraits comptables.',
    ref: 'RA Standard 2020 v1.3, §2.1.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-05',
    cat: 'tracabilite',
    titre: 'Modèle de chaîne de traçabilité défini',
    desc: 'Choix entre Identity Preserved (IP), Segregated, Mass Balance documenté par produit. Méthodologie cohérente avec audits.',
    crit: 'majeure',
    preuve: 'Document décrivant le modèle par produit + procédure.',
    ref: 'RA Standard 2020 v1.3, §2.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-06',
    cat: 'tracabilite',
    titre: 'Bilan matière mensuel RA',
    desc: 'Suivi mensuel : volumes RA achetés / produits / vendus / stocks. Aucun écart inexpliqué supérieur à 3%.',
    crit: 'majeure',
    preuve: 'Bilan matière mensuel signé.',
    ref: 'RA Standard 2020 v1.3, §2.2.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-07',
    cat: 'tracabilite',
    titre: 'Aucun mélange RA / non-RA en chaîne IP',
    desc: 'En modèle Identity Preserved : aucun mélange autorisé entre lots RA et non-RA. Séparation physique stricte.',
    crit: 'majeure',
    preuve: 'Plan d\'unité + vérification automatique sur lots composites.',
    ref: 'RA Standard 2020 v1.3, §2.2.1',
    auto: 1, regle: 'MELANGE_BIO_CONV',
  },
  {
    code: 'RA-TRAC-08',
    cat: 'tracabilite',
    titre: 'Identification physique des lots RA',
    desc: 'Marquage clair sur emballages, palettes, conteneurs : code lot, mention RA, n° licence. Distinction visuelle immédiate.',
    crit: 'majeure',
    preuve: 'Photos étiquettes + plan marquage.',
    ref: 'RA Standard 2020 v1.3, §2.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-09',
    cat: 'tracabilite',
    titre: 'Documentation transactions complète',
    desc: 'Pour chaque achat/vente RA : facture, BL, documents de transport mentionnant statut RA, volume, lot.',
    crit: 'majeure',
    preuve: 'Échantillon de transactions documentées.',
    ref: 'RA Standard 2020 v1.3, §2.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-10',
    cat: 'tracabilite',
    titre: 'Test traçabilité simulé semestriel',
    desc: 'Simulation semestrielle : choisir 1 lot vendu, retracer en moins de 4h jusqu\'aux producteurs initiaux. Documenté.',
    crit: 'majeure',
    preuve: 'Rapports test traçabilité (2/an).',
    ref: 'RA Standard 2020 v1.3, §2.3.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-11',
    cat: 'tracabilite',
    titre: 'Conservation registres minimum 5 ans',
    desc: 'Tous registres RA (transactions, certificats, bilans, audits) archivés ≥ 5 ans.',
    crit: 'majeure',
    preuve: 'Politique archivage + démonstration accès.',
    ref: 'RA Standard 2020 v1.3, §2.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-12',
    cat: 'tracabilite',
    titre: 'Transactions RA déclarées sous 30 jours',
    desc: 'Toute transaction RA déclarée sur RACP dans les 30 jours. Pas de transactions rétroactives non justifiées.',
    crit: 'mineure',
    preuve: 'Délais de saisie sur RACP.',
    ref: 'RA Standard 2020 v1.3, §2.1.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-TRAC-13',
    cat: 'tracabilite',
    titre: 'Audit annuel sur traçabilité',
    desc: 'Inclus dans audit interne et externe RA : vérification rapprochement RACP / comptabilité / stocks physiques.',
    crit: 'majeure',
    preuve: 'Rapports audit avec section traçabilité.',
    ref: 'RA Standard 2020 v1.3, §2.5',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 3 — REVENU & PARTAGE RESPONSABILITÉ (8 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-INC-01',
    cat: 'gouvernance',
    titre: 'Différentiel de durabilité (Sustainability Differential) versé',
    desc: 'Acheteur paie un Sustainability Differential (SD) en supplément du prix de marché, montant fixe par produit. Versé directement aux producteurs.',
    crit: 'majeure',
    preuve: 'Contrats commerciaux mentionnant SD + bons d\'achat producteurs.',
    ref: 'RA Standard 2020 v1.3, Chapitre 3 §3.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-INC-02',
    cat: 'gouvernance',
    titre: 'Investissement de durabilité (Sustainability Investment)',
    desc: 'Investissement supplémentaire (SI) versé par acheteur pour financer le plan d\'amélioration des producteurs. Plan d\'investissement co-construit.',
    crit: 'majeure',
    preuve: 'Plan d\'investissement signé acheteur-producteurs + contrats SI.',
    ref: 'RA Standard 2020 v1.3, §3.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-INC-03',
    cat: 'gouvernance',
    titre: 'Comptabilité séparée du SD et SI',
    desc: 'Les montants SD et SI tracés dans comptabilité analytique séparée. Réconciliation avec contrats acheteur.',
    crit: 'majeure',
    preuve: 'Plan comptable analytique + livre comptable.',
    ref: 'RA Standard 2020 v1.3, §3.1 + 3.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-INC-04',
    cat: 'gouvernance',
    titre: 'Communication transparente du SD aux producteurs',
    desc: 'Producteurs informés du montant exact du SD versé pour leurs ventes. Affichage public, bulletins, AG.',
    crit: 'majeure',
    preuve: 'Communications producteurs + affichage.',
    ref: 'RA Standard 2020 v1.3, §3.1.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-INC-05',
    cat: 'gouvernance',
    titre: 'Plan d\'investissement annuel approuvé',
    desc: 'Plan d\'investissement annuel décrit projets, montants, bénéficiaires. Approuvé par CA producteurs et acheteur.',
    crit: 'majeure',
    preuve: 'Document plan investissement signé.',
    ref: 'RA Standard 2020 v1.3, §3.2.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-INC-06',
    cat: 'gouvernance',
    titre: 'Évaluation impact des investissements',
    desc: 'Évaluation à 12 mois des projets financés par SI : indicateurs, bénéficiaires, leçons apprises. Présenté en AG.',
    crit: 'mineure',
    preuve: 'Rapports évaluation projets.',
    ref: 'RA Standard 2020 v1.3, §3.2.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-INC-07',
    cat: 'gouvernance',
    titre: 'Mesure du Living Income (revenu vital)',
    desc: 'Mesure périodique de l\'écart entre revenus moyens producteurs et seuil Living Income national. Plan de réduction écart.',
    crit: 'mineure',
    preuve: 'Étude Living Income + plan réduction écart.',
    ref: 'RA Standard 2020 v1.3, §3.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-INC-08',
    cat: 'gouvernance',
    titre: 'Pas de prélèvements abusifs sur producteurs',
    desc: 'Aucun prélèvement non justifié (frais administratifs excessifs) sur prix versés aux producteurs. Transparence totale.',
    crit: 'majeure',
    preuve: 'Détail frais prélevés + justification.',
    ref: 'RA Standard 2020 v1.3, §3.1.3',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 4 — DROITS HUMAINS & TRAVAIL (20 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-HR-01',
    cat: 'social_travail',
    titre: 'Politique droits humains alignée UN Guiding Principles',
    desc: 'Politique signée direction couvrant : non-discrimination, liberté association, salaire vital, conditions sécurité, protection enfants, vulnérables.',
    crit: 'majeure',
    preuve: 'Document politique signé.',
    ref: 'RA Standard 2020 v1.3, Chapitre 4 §4.1.1 + UN Guiding Principles',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-02',
    cat: 'social_travail',
    titre: 'Aucun travail forcé ou en servitude',
    desc: 'Aucune forme de travail forcé. Pas de retention papiers, pas de servitude pour dette, liberté de quitter emploi.',
    crit: 'majeure',
    preuve: 'Charte + entretiens employés lors audit.',
    ref: 'RA Standard 2020 v1.3, §4.2 + ILO C29/C105',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-03',
    cat: 'social_travail',
    titre: 'Pas de travail des enfants < 15 ans',
    desc: 'Travail des enfants < 15 ans interdit. Aide familiale légère hors heures scolaires acceptée si pas dangereuse.',
    crit: 'majeure',
    preuve: 'Registre personnel avec dates de naissance.',
    ref: 'RA Standard 2020 v1.3, §4.3 + ILO C138',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-04',
    cat: 'social_travail',
    titre: 'Système de surveillance protection enfance',
    desc: 'Système de monitoring actif : visites, entretiens enfants, signalements. Procédure de remédiation si cas détecté (pas de licenciement automatique).',
    crit: 'majeure',
    preuve: 'Procédure monitoring + registre cas (anonymisé).',
    ref: 'RA Standard 2020 v1.3, §4.3.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-05',
    cat: 'social_travail',
    titre: 'Pas de travaux dangereux pour 15-18 ans',
    desc: 'Liste écrite des travaux interdits aux mineurs 15-18 ans : pesticides, machines, charges lourdes, travail nuit, hauteurs.',
    crit: 'majeure',
    preuve: 'Liste travaux interdits + registre personnel jeunes.',
    ref: 'RA Standard 2020 v1.3, §4.3 + ILO C182',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-06',
    cat: 'social_travail',
    titre: 'Salaire minimum légal national respecté',
    desc: 'Tous travailleurs reçoivent ≥ SMIG malgache. Bulletins paie. Engagement vers Living Wage à terme.',
    crit: 'majeure',
    preuve: 'Bulletins paie + référence SMIG.',
    ref: 'RA Standard 2020 v1.3, §4.4 + Code travail malgache',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-07',
    cat: 'social_travail',
    titre: 'Plan progression vers Living Wage',
    desc: 'Plan documenté de progression vers le salaire vital (Living Wage) défini par étude indépendante (ex. Anker Living Wage).',
    crit: 'mineure',
    preuve: 'Plan Living Wage + étude de référence.',
    ref: 'RA Standard 2020 v1.3, §4.4.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-08',
    cat: 'social_travail',
    titre: 'Heures de travail conformes (max 48h/semaine)',
    desc: 'Durée légale respectée. Heures supplémentaires volontaires, majorées, limitées (max 12h supp/semaine).',
    crit: 'majeure',
    preuve: 'Registre heures + bulletins paie.',
    ref: 'RA Standard 2020 v1.3, §4.4.4 + ILO C1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-09',
    cat: 'social_travail',
    titre: 'Repos hebdomadaire 24h continues',
    desc: 'Tous les travailleurs bénéficient d\'au moins 24h de repos continu par semaine.',
    crit: 'majeure',
    preuve: 'Plannings + registre des présences.',
    ref: 'RA Standard 2020 v1.3, §4.4.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-10',
    cat: 'social_travail',
    titre: 'Liberté association et négociation collective',
    desc: 'Liberté constitution syndicats, adhésion sans sanction. Si syndicat existant, négociation collective de bonne foi.',
    crit: 'majeure',
    preuve: 'Politique liberté association + absence litiges.',
    ref: 'RA Standard 2020 v1.3, §4.5 + ILO C87/C98',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-11',
    cat: 'social_travail',
    titre: 'Comité représentation employés',
    desc: 'Si pas de syndicat : comité d\'employés élus représentant les travailleurs auprès direction. Réunions régulières.',
    crit: 'mineure',
    preuve: 'PV élections comité + PV réunions.',
    ref: 'RA Standard 2020 v1.3, §4.5.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-12',
    cat: 'social_travail',
    titre: 'Politique anti-discrimination active',
    desc: 'Politique anti-discrimination écrite, formation managers, processus recrutement basé compétences. Statistiques diversité suivies.',
    crit: 'majeure',
    preuve: 'Politique + formations + statistiques.',
    ref: 'RA Standard 2020 v1.3, §4.6 + ILO C100/C111',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-13',
    cat: 'social_travail',
    titre: 'Égalité salariale F/H pour travail de valeur égale',
    desc: 'À compétences et poste égaux, salaires égaux entre femmes et hommes. Audit interne salarial recommandé.',
    crit: 'majeure',
    preuve: 'Grille salariale + audit interne salaires.',
    ref: 'RA Standard 2020 v1.3, §4.6.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-14',
    cat: 'social_travail',
    titre: 'Politique anti-harcèlement (sexuel et moral)',
    desc: 'Politique écrite, procédure signalement confidentielle, formation managers et personnel. Sanctions documentées.',
    crit: 'majeure',
    preuve: 'Politique + registre formations + registre signalements.',
    ref: 'RA Standard 2020 v1.3, §4.6.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-15',
    cat: 'social_travail',
    titre: 'Conditions de logement décentes (si fournies)',
    desc: 'Si logements fournis : conformité standards (eau, électricité, sanitaires séparés H/F, espace minimum, sécurité incendie, chauffage).',
    crit: 'majeure',
    preuve: 'Photos + checklist conformité.',
    ref: 'RA Standard 2020 v1.3, §4.7',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-16',
    cat: 'social_travail',
    titre: 'Eau potable accessible aux travailleurs',
    desc: 'Eau potable accessible gratuitement sur tous les lieux de travail. Distance maximale 250m du poste.',
    crit: 'majeure',
    preuve: 'Photos points eau + plan d\'aménagement.',
    ref: 'RA Standard 2020 v1.3, §4.7.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-17',
    cat: 'social_travail',
    titre: 'Sanitaires propres séparés homme/femme',
    desc: 'Toilettes propres, séparées par genre, en nombre suffisant (1 pour 25 travailleurs). Lavabos avec savon.',
    crit: 'majeure',
    preuve: 'Photos sanitaires + plan d\'aménagement.',
    ref: 'RA Standard 2020 v1.3, §4.7.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-18',
    cat: 'social_travail',
    titre: 'Procédure de licenciement encadrée',
    desc: 'Licenciement sur motif sérieux uniquement. Procédure : avertissements, entretien, préavis, indemnités.',
    crit: 'mineure',
    preuve: 'Procédure + dossiers anonymisés.',
    ref: 'RA Standard 2020 v1.3, §4.4.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-19',
    cat: 'social_travail',
    titre: 'Contrats écrits pour tous permanents',
    desc: 'Tous salariés permanents ont contrat écrit signé. Saisonniers : contrat selon législation.',
    crit: 'majeure',
    preuve: 'Échantillon contrats.',
    ref: 'RA Standard 2020 v1.3, §4.4.1 + Code travail',
    auto: 0, regle: null,
  },
  {
    code: 'RA-HR-20',
    cat: 'social_travail',
    titre: 'CNAPS cotisations à jour',
    desc: 'Tous salariés permanents inscrits CNAPS. Cotisations versées dans délais.',
    crit: 'majeure',
    preuve: 'Quittances cotisations < 3 mois.',
    ref: 'RA Standard 2020 v1.3 + Code travail malgache',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 5 — SANTÉ & SÉCURITÉ TRAVAILLEURS (10 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-OHS-01',
    cat: 'social_travail',
    titre: 'Évaluation des risques professionnels',
    desc: 'Évaluation des risques par poste de travail : pesticides, machines, charges, postures. Plan d\'actions.',
    crit: 'majeure',
    preuve: 'Document évaluation risques + plan actions.',
    ref: 'RA Standard 2020 v1.3, Chapitre 5 §5.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-OHS-02',
    cat: 'social_travail',
    titre: 'EPI fournis gratuitement et adaptés',
    desc: 'EPI gratuits (gants, masques, lunettes, bottes, casques) adaptés aux risques. Formation usage. Renouvelés selon usure.',
    crit: 'majeure',
    preuve: 'Registre remise EPI + photos terrain.',
    ref: 'RA Standard 2020 v1.3, §5.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-OHS-03',
    cat: 'social_travail',
    titre: 'Formation sécurité annuelle',
    desc: 'Formation annuelle tous salariés : risques poste, EPI, premiers secours, conduite à tenir incident.',
    crit: 'majeure',
    preuve: 'Registre formations + attestations.',
    ref: 'RA Standard 2020 v1.3, §5.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-OHS-04',
    cat: 'social_travail',
    titre: 'Trousse premiers secours et secouristes formés',
    desc: 'Trousses premiers secours accessibles. Au moins 1 secouriste formé pour 25 travailleurs. Numéros urgence affichés.',
    crit: 'majeure',
    preuve: 'Photos trousses + attestations secouristes.',
    ref: 'RA Standard 2020 v1.3, §5.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-OHS-05',
    cat: 'social_travail',
    titre: 'Visite médicale d\'embauche et annuelle',
    desc: 'Visite médicale obligatoire à l\'embauche puis annuelle pour postes à risque (manipulation pesticides, machines).',
    crit: 'majeure',
    preuve: 'Certificats médicaux < 12 mois.',
    ref: 'RA Standard 2020 v1.3, §5.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-OHS-06',
    cat: 'social_travail',
    titre: 'Registre des accidents du travail',
    desc: 'Tous accidents et incidents tracés : date, victime, gravité, cause, action corrective. Analyse trimestrielle des KPI.',
    crit: 'majeure',
    preuve: 'Registre accidents + analyses.',
    ref: 'RA Standard 2020 v1.3, §5.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-OHS-07',
    cat: 'social_travail',
    titre: 'Pas d\'application pesticides par femmes enceintes',
    desc: 'Femmes enceintes ou allaitantes pas exposées aux pesticides ni produits dangereux. Reaffectation temporaire à postes sûrs.',
    crit: 'majeure',
    preuve: 'Politique écrite + registre reaffectations.',
    ref: 'RA Standard 2020 v1.3, §5.2.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-OHS-08',
    cat: 'social_travail',
    titre: 'Délai de réentrée après application pesticides',
    desc: 'Respect strict du délai de réentrée (REI) après pulvérisation pesticide. Affichage zones traitées avec date/heure.',
    crit: 'majeure',
    preuve: 'Procédure REI + signalisation zones.',
    ref: 'RA Standard 2020 v1.3, §5.2.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-OHS-09',
    cat: 'social_travail',
    titre: 'Locaux de stockage pesticides sécurisés',
    desc: 'Local fermé clé, ventilé, sol étanche, pictogrammes danger, EPI proximité, fiches sécurité affichées.',
    crit: 'majeure',
    preuve: 'Photos local + plan + procédure accès.',
    ref: 'RA Standard 2020 v1.3, §5.2.7',
    auto: 0, regle: null,
  },
  {
    code: 'RA-OHS-10',
    cat: 'social_travail',
    titre: 'Plan d\'urgence et exercices évacuation',
    desc: 'Plan d\'urgence (incendie, chimique, météo extrême). Exercices évacuation annuels. Sorties secours signalées.',
    crit: 'mineure',
    preuve: 'Plan d\'urgence + comptes rendus exercices.',
    ref: 'RA Standard 2020 v1.3, §5.7',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 6 — FORÊTS ET BIODIVERSITÉ (15 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-ENV-01',
    cat: 'environnement',
    titre: 'Cartographie GPS de toutes parcelles',
    desc: 'Coordonnées GPS de toutes parcelles dans un fichier unique (KML, GeoJSON, shapefile). Fichier validé par auditeur.',
    crit: 'majeure',
    preuve: 'Fichier KML/shapefile à jour + AgroMap.',
    ref: 'RA Standard 2020 v1.3, Chapitre 6 §6.1.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-02',
    cat: 'environnement',
    titre: 'Vérification déforestation post-2014 par satellite',
    desc: 'Aucune déforestation ou conversion d\'écosystème naturel après 1er janvier 2014. Vérification via Global Forest Watch, Sentinel-2 ou outils RA.',
    crit: 'majeure',
    preuve: 'Captures images satellite historiques + déclaration sur honneur producteurs.',
    ref: 'RA Standard 2020 v1.3, §6.1.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-03',
    cat: 'environnement',
    titre: 'Identification HCV (High Conservation Value)',
    desc: 'Identification zones HCV proches : forêts primaires, habitats espèces menacées, services écosystémiques, zones sacrées. Mesures protection.',
    crit: 'majeure',
    preuve: 'Cartographie HCV + plan de protection.',
    ref: 'RA Standard 2020 v1.3, §6.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-04',
    cat: 'environnement',
    titre: 'Préservation aires protégées (parcs, réserves)',
    desc: 'Aucune activité agricole dans aires protégées. Zones tampons respectées (minimum 100m bordure parc national).',
    crit: 'majeure',
    preuve: 'Cartographie aires protégées + plan parcellaire.',
    ref: 'RA Standard 2020 v1.3, §6.2.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-05',
    cat: 'environnement',
    titre: 'Pourcentage minimum couvert d\'ombrage (cacao, café)',
    desc: 'Plantations cacao et café : minimum 12-15 arbres ombrage par hectare avec espèces diversifiées (≥ 10 espèces).',
    crit: 'majeure',
    preuve: 'Inventaire ombrage + cartographie.',
    ref: 'RA Standard 2020 v1.3, §6.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-06',
    cat: 'environnement',
    titre: 'Minimum 10% surface en végétation naturelle',
    desc: 'Sur ferme certifiée : minimum 10% de la SAU maintenue en végétation naturelle (haies, bosquets, mares, bandes enherbées).',
    crit: 'majeure',
    preuve: 'Cartographie + photos zones naturelles.',
    ref: 'RA Standard 2020 v1.3, §6.3.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-07',
    cat: 'environnement',
    titre: 'Plantation espèces locales/indigènes prioritaires',
    desc: 'Pour reboisement, ombrage, haies : espèces locales ou indigènes prioritaires. Évite espèces invasives.',
    crit: 'mineure',
    preuve: 'Liste espèces plantées + justification botanique.',
    ref: 'RA Standard 2020 v1.3, §6.3.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-08',
    cat: 'environnement',
    titre: 'Aucune chasse, capture espèces protégées',
    desc: 'Interdiction chasse, piégeage, capture espèces protégées (Convention CITES). Politique affichée.',
    crit: 'majeure',
    preuve: 'Politique + affichage.',
    ref: 'RA Standard 2020 v1.3, §6.4 + CITES',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-09',
    cat: 'environnement',
    titre: 'Inventaire faune et flore présente',
    desc: 'Inventaire écologique simplifié sur l\'exploitation : espèces protégées présentes, espèces invasives à contrôler.',
    crit: 'mineure',
    preuve: 'Inventaire signé.',
    ref: 'RA Standard 2020 v1.3, §6.4.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-10',
    cat: 'environnement',
    titre: 'Lutte contre espèces invasives',
    desc: 'Identification et plan de lutte contre espèces invasives (Lantana, Eucalyptus expansif, etc.) sur l\'exploitation.',
    crit: 'mineure',
    preuve: 'Plan lutte invasives.',
    ref: 'RA Standard 2020 v1.3, §6.4.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-11',
    cat: 'environnement',
    titre: 'Bandes tampons cours d\'eau respectées',
    desc: 'Bandes enherbées/boisées minimum 5m (petits cours) à 30m (rivières) le long cours d\'eau. Pas d\'activité agricole.',
    crit: 'majeure',
    preuve: 'Cartographie + photos.',
    ref: 'RA Standard 2020 v1.3, §6.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-12',
    cat: 'environnement',
    titre: 'Pas d\'activité sur pentes > 30%',
    desc: 'Restrictions sur pentes fortes : pas de cultures annuelles si pente > 30% sans terrasses/aménagements anti-érosion.',
    crit: 'majeure',
    preuve: 'Cartographie pentes + aménagements.',
    ref: 'RA Standard 2020 v1.3, §6.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-13',
    cat: 'environnement',
    titre: 'Brûlage agricole encadré (interdit en règle générale)',
    desc: 'Brûlage interdit pour préparation parcelles, gestion résidus, défrichage. Exceptions strictes (lutte ravageur spécifique avec autorisation).',
    crit: 'majeure',
    preuve: 'Politique anti-brûlage + photos parcelles.',
    ref: 'RA Standard 2020 v1.3, §6.7',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-14',
    cat: 'environnement',
    titre: 'Connectivité écologique entre parcelles',
    desc: 'Plan favorisant connectivité entre zones boisées : haies vives, corridors écologiques, conservation sentiers naturels.',
    crit: 'mineure',
    preuve: 'Cartographie corridors.',
    ref: 'RA Standard 2020 v1.3, §6.4.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-ENV-15',
    cat: 'environnement',
    titre: 'Restauration zones dégradées',
    desc: 'Plan de restauration des zones dégradées (érodées, défrichées avant 2014, abandonnées) avec espèces indigènes.',
    crit: 'mineure',
    preuve: 'Plan restauration + photos avant/après.',
    ref: 'RA Standard 2020 v1.3, §6.3.6',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 7 — AGRICULTURE & PRATIQUES (15 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-AGR-01',
    cat: 'pratiques_culturales',
    titre: 'Plan annuel de gestion agronomique',
    desc: 'Plan détaillant : planning cultural, fertilisation, protection cultures, irrigation, récolte. Validé par responsable technique.',
    crit: 'majeure',
    preuve: 'Document plan agronomique annuel.',
    ref: 'RA Standard 2020 v1.3, Chapitre 7 §7.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-02',
    cat: 'pratiques_culturales',
    titre: 'Lutte intégrée prioritaire (IPM)',
    desc: 'Approche IPM (Integrated Pest Management) prioritaire : prévention, surveillance ravageurs, seuils intervention, méthodes biologiques avant chimiques.',
    crit: 'majeure',
    preuve: 'Plan IPM par culture + registre observations.',
    ref: 'RA Standard 2020 v1.3, §7.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-03',
    cat: 'pratiques_culturales',
    titre: 'Liste pesticides interdits RA respectée',
    desc: 'Conformité avec RA Prohibited Pesticides List 2024 (très large, alignée WHO 1A/1B + persistants). Liste plus stricte que Codex.',
    crit: 'majeure',
    preuve: 'Inventaire pesticides + comparaison liste RA.',
    ref: 'RA Prohibited Pesticides List 2024',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-04',
    cat: 'pratiques_culturales',
    titre: 'Pesticides Restreints sous surveillance',
    desc: 'Si pesticides Restricted Use Pesticides (RUP) utilisés : justification, autorisation préalable, suivi rigoureux, plan de réduction.',
    crit: 'majeure',
    preuve: 'Liste pesticides RUP + justifications + plan de réduction.',
    ref: 'RA Standard 2020 v1.3, §7.2.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-05',
    cat: 'pratiques_culturales',
    titre: 'Application pesticides par opérateurs formés',
    desc: 'Application uniquement par opérateurs formés (formation annuelle), équipés (EPI), majeurs. Femmes enceintes exclues.',
    crit: 'majeure',
    preuve: 'Attestations formation + registre applications.',
    ref: 'RA Standard 2020 v1.3, §7.2.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-06',
    cat: 'pratiques_culturales',
    titre: 'Calibrage matériel pulvérisation annuel',
    desc: 'Pulvérisateurs vérifiés et calibrés annuellement : débit, pression, buses. Réglage adapté à chaque culture.',
    crit: 'mineure',
    preuve: 'Registre calibrage matériel.',
    ref: 'RA Standard 2020 v1.3, §7.2.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-07',
    cat: 'pratiques_culturales',
    titre: 'Plan de fertilisation raisonné',
    desc: 'Plan fertilisation basé sur analyses sol périodiques (3-5 ans), besoins culture, restitution. Évite sur-fertilisation.',
    crit: 'majeure',
    preuve: 'Plan fertilisation + analyses sol.',
    ref: 'RA Standard 2020 v1.3, §7.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-08',
    cat: 'pratiques_culturales',
    titre: 'Préférence aux engrais organiques',
    desc: 'Engrais organiques (compost, fumier) prioritaires. Engrais minéraux complémentaires uniquement.',
    crit: 'mineure',
    preuve: 'Bilan annuel apports organiques vs minéraux.',
    ref: 'RA Standard 2020 v1.3, §7.3.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-09',
    cat: 'pratiques_culturales',
    titre: 'Couverture végétale permanente du sol',
    desc: 'Limitation sols nus : couvert végétal, mulch, cultures associées, paillage. Particulièrement important sur tanety pentu.',
    crit: 'mineure',
    preuve: 'Photos parcelles + plan couverts.',
    ref: 'RA Standard 2020 v1.3, §7.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-10',
    cat: 'pratiques_culturales',
    titre: 'Rotation cultures annuelles',
    desc: 'Pour cultures annuelles : rotation pluriannuelle incluant légumineuses. Évite épuisement sol et pression maladies.',
    crit: 'mineure',
    preuve: 'Plan rotation par parcelle.',
    ref: 'RA Standard 2020 v1.3, §7.4.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-11',
    cat: 'pratiques_culturales',
    titre: 'Aucun OGM utilisé',
    desc: 'Interdiction absolue OGM. Vigilance soja/maïs si rotation. Attestations fournisseurs.',
    crit: 'majeure',
    preuve: 'Attestations sans OGM.',
    ref: 'RA Standard 2020 v1.3, §7.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-12',
    cat: 'pratiques_culturales',
    titre: 'Semences locales et adaptées privilégiées',
    desc: 'Semences locales, variétés rustiques, adaptées au climat MDG préférées. Documentation choix.',
    crit: 'recommandation',
    preuve: 'Liste variétés + justification.',
    ref: 'RA Standard 2020 v1.3, §7.5.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-13',
    cat: 'pratiques_culturales',
    titre: 'Densité plantation respectée',
    desc: 'Densités plantation conformes ITK : suffisamment espacé pour aération, biodiversité, accès travailleurs.',
    crit: 'mineure',
    preuve: 'Plan plantation + densité par hectare.',
    ref: 'RA Standard 2020 v1.3, §7.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-14',
    cat: 'pratiques_culturales',
    titre: 'Taille raisonnée pour pérennes',
    desc: 'Tailles formation, fructification, sanitaires selon physiologie. Outils propres pour éviter propagation maladies.',
    crit: 'mineure',
    preuve: 'Calendrier taille + registre opérations.',
    ref: 'RA Standard 2020 v1.3, §7.6.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-AGR-15',
    cat: 'pratiques_culturales',
    titre: 'Délai conversion pour pérennes : 3 ans',
    desc: 'Pour vanille, café, cacao, etc. : délai 3 ans entre dernière application pesticide interdit et première récolte certifiable RA.',
    crit: 'majeure',
    preuve: 'Calcul automatique délai.',
    ref: 'RA Standard 2020 v1.3, §7.2.4',
    auto: 1, regle: 'DELAI_CONVERSION_BIO',
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 8 — RESSOURCES NATURELLES (12 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-WATER-01',
    cat: 'environnement',
    titre: 'Plan de gestion eau documenté',
    desc: 'Plan : sources eau identifiées, prélèvements estimés, irrigation économe, qualité eau process, rejets traités.',
    crit: 'majeure',
    preuve: 'Plan gestion eau signé.',
    ref: 'RA Standard 2020 v1.3, Chapitre 8 §8.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-02',
    cat: 'environnement',
    titre: 'Mesure des prélèvements eau',
    desc: 'Compteurs ou estimations sur principaux prélèvements. Suivi mensuel. Objectifs réduction.',
    crit: 'mineure',
    preuve: 'Registre relevés compteurs ou estimations.',
    ref: 'RA Standard 2020 v1.3, §8.1.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-03',
    cat: 'environnement',
    titre: 'Irrigation économe (goutte-à-goutte préféré)',
    desc: 'Systèmes irrigation économes : goutte-à-goutte, micro-aspersion. Évite irrigation gravitaire si alternatives possibles.',
    crit: 'mineure',
    preuve: 'Description systèmes + photos.',
    ref: 'RA Standard 2020 v1.3, §8.1.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-04',
    cat: 'environnement',
    titre: 'Eau de process potable analysée',
    desc: 'Eau utilisée en transformation (lavage, scaldage) potable, analyses bactério semestrielles minimum.',
    crit: 'majeure',
    preuve: 'Bulletins analyse eau < 6 mois.',
    ref: 'RA Standard 2020 v1.3, §8.1.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-05',
    cat: 'environnement',
    titre: 'Traitement eaux usées avant rejet',
    desc: 'Eaux usées (transformation, sanitaires) traitées avant rejet : filtration, décantation, fosses septiques. Pas de rejet brut dans cours d\'eau.',
    crit: 'majeure',
    preuve: 'Description installations + photos.',
    ref: 'RA Standard 2020 v1.3, §8.1.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-06',
    cat: 'environnement',
    titre: 'Aucune contamination des eaux par pesticides',
    desc: 'Stockage pesticides éloigné cours d\'eau. Lavage matériel sur aire dédiée avec récupération. Bandes tampons strictes.',
    crit: 'majeure',
    preuve: 'Photos installations + plan parcellaire.',
    ref: 'RA Standard 2020 v1.3, §8.1.7',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-07',
    cat: 'environnement',
    titre: 'Plan énergie et émissions GES',
    desc: 'Inventaire des sources énergie (carburants, électricité, biomasse). Calcul empreinte carbone. Objectifs réduction.',
    crit: 'mineure',
    preuve: 'Plan énergie + bilan carbone.',
    ref: 'RA Standard 2020 v1.3, §8.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-08',
    cat: 'environnement',
    titre: 'Énergies renouvelables encouragées',
    desc: 'Solaire (séchage, eau chaude), biomasse (bois géré durablement), hydroélectricité si disponible. Priorité sur énergies fossiles.',
    crit: 'recommandation',
    preuve: 'Description sources énergie + investissements renouvelables.',
    ref: 'RA Standard 2020 v1.3, §8.2.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-09',
    cat: 'environnement',
    titre: 'Tri sélectif des déchets',
    desc: 'Tri : organiques (compost), recyclables (plastique, métal, verre, papier), dangereux (pesticides, batteries), ménagers.',
    crit: 'majeure',
    preuve: 'Plan tri + photos zones.',
    ref: 'RA Standard 2020 v1.3, §8.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-10',
    cat: 'environnement',
    titre: 'Élimination déchets dangereux par filière agréée',
    desc: 'Emballages pesticides triple-rincés et collectés via filière agréée (ADIVALOR équivalent local). Pas de stockage prolongé.',
    crit: 'majeure',
    preuve: 'Contrats collecteur + bordereaux d\'enlèvement.',
    ref: 'RA Standard 2020 v1.3, §8.3.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-11',
    cat: 'environnement',
    titre: 'Pas de brûlage déchets non autorisés',
    desc: 'Brûlage à l\'air libre interdit pour plastiques, pneus, batteries, chiffons souillés.',
    crit: 'majeure',
    preuve: 'Politique + photos.',
    ref: 'RA Standard 2020 v1.3, §8.3.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-WATER-12',
    cat: 'environnement',
    titre: 'Compostage des déchets organiques',
    desc: 'Déchets organiques (résidus récolte, pulpes, fumier) compostés sur site et restitués au sol.',
    crit: 'mineure',
    preuve: 'Photos zones compostage + procédure.',
    ref: 'RA Standard 2020 v1.3, §8.3.5',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 9 — CLIMAT (5 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-CLIM-01',
    cat: 'environnement',
    titre: 'Évaluation vulnérabilité climatique',
    desc: 'Identification risques climatiques : sécheresse, cyclones MDG, érosion, ravageurs émergents. Plan d\'adaptation.',
    crit: 'majeure',
    preuve: 'Document évaluation + plan adaptation.',
    ref: 'RA Standard 2020 v1.3, Chapitre 9 §9.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-CLIM-02',
    cat: 'environnement',
    titre: 'Pratiques climate-smart agriculture',
    desc: 'Pratiques résilientes : variétés adaptées, agroforesterie (séquestration carbone), sols couverts, eau économe.',
    crit: 'mineure',
    preuve: 'Description pratiques climate-smart appliquées.',
    ref: 'RA Standard 2020 v1.3, §9.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-CLIM-03',
    cat: 'environnement',
    titre: 'Mesure stockage carbone agroforestier',
    desc: 'Pour plantations en agroforesterie : estimation stockage carbone (densité arbres, biomasse). Outils RA disponibles.',
    crit: 'mineure',
    preuve: 'Calcul stockage carbone par hectare.',
    ref: 'RA Standard 2020 v1.3, §9.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-CLIM-04',
    cat: 'environnement',
    titre: 'Plan de continuité activité (cyclones, sécheresse)',
    desc: 'Pour MDG : plan continuité activité face aux cyclones (bâtiments solides, stocks réserve, communication d\'urgence).',
    crit: 'mineure',
    preuve: 'Plan continuité + exercices.',
    ref: 'RA Standard 2020 v1.3, §9.1.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-CLIM-05',
    cat: 'environnement',
    titre: 'Formation producteurs au changement climatique',
    desc: 'Formation annuelle producteurs : impacts climat sur cultures, pratiques d\'adaptation, anticipation.',
    crit: 'mineure',
    preuve: 'Programmes formation + attestations.',
    ref: 'RA Standard 2020 v1.3, §9.4',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 10 — POST-RÉCOLTE & QUALITÉ (10 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-PR-01',
    cat: 'gestion_post_recolte',
    titre: 'Locaux post-récolte adaptés et propres',
    desc: 'Locaux séchage, tri, stockage propres, ventilés, protégés nuisibles. Plan de nettoyage périodique.',
    crit: 'majeure',
    preuve: 'Photos locaux + plan nettoyage.',
    ref: 'RA Standard 2020 v1.3, Chapitre 10 §10.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-PR-02',
    cat: 'gestion_post_recolte',
    titre: 'Étape post-récolte documentée pour tout lot',
    desc: 'Tout lot clôturé doit avoir au moins une étape post-récolte enregistrée.',
    crit: 'majeure',
    preuve: 'Étapes ExportTrack pour chaque lot.',
    ref: 'RA Standard 2020 v1.3, §10.2',
    auto: 1, regle: 'ETAPE_MANQUANTE',
  },
  {
    code: 'RA-PR-03',
    cat: 'gestion_post_recolte',
    titre: 'Séparation RA / non-RA en stockage',
    desc: 'Lots RA stockés séparément des conventionnels (zones distinctes ou plages temporelles).',
    crit: 'majeure',
    preuve: 'Plan stockage + procédure.',
    ref: 'RA Standard 2020 v1.3, §10.3',
    auto: 1, regle: 'MELANGE_BIO_CONV',
  },
  {
    code: 'RA-PR-04',
    cat: 'gestion_post_recolte',
    titre: 'Lutte nuisibles avec produits autorisés',
    desc: 'Lutte rongeurs/insectes avec moyens physiques, CO2, terre de diatomée. Pas de fumigation chimique sans dérogation.',
    crit: 'majeure',
    preuve: 'Plan lutte + factures produits.',
    ref: 'RA Standard 2020 v1.3, §10.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-PR-05',
    cat: 'qualite_securite',
    titre: 'Contrôle qualité au minimum à réception',
    desc: 'Contrôle qualité systématique à réception (humidité, défauts visuels) et à expédition. Tracé.',
    crit: 'majeure',
    preuve: 'Registre contrôles qualité.',
    ref: 'RA Standard 2020 v1.3, §10.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-PR-06',
    cat: 'qualite_securite',
    titre: 'Analyses contaminants conformes UE/USA',
    desc: 'Analyses conformes aux LMR du marché destination (UE 2023/915 ou USDA NOP). Bulletins par lot.',
    crit: 'majeure',
    preuve: 'Bulletins analyse.',
    ref: 'RA Standard 2020 v1.3, §10.5.3',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'RA-PR-07',
    cat: 'qualite_securite',
    titre: 'Spécifications acheteurs respectées',
    desc: 'Pour chaque acheteur : spécifications produit (calibre, humidité, taux défauts) respectées et documentées.',
    crit: 'majeure',
    preuve: 'Bulletins qualité par expédition.',
    ref: 'RA Standard 2020 v1.3, §10.5.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-PR-08',
    cat: 'qualite_securite',
    titre: 'Procédure non-conformité qualité',
    desc: 'Si lot non conforme : isolement, enquête cause, action corrective, notification client si déjà expédié.',
    crit: 'majeure',
    preuve: 'Procédure + registre NC.',
    ref: 'RA Standard 2020 v1.3, §10.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-PR-09',
    cat: 'qualite_securite',
    titre: 'Échantillothèque conservée 6 mois minimum',
    desc: 'Échantillons conservés ≥ 6 mois après expédition pour contre-analyses.',
    crit: 'mineure',
    preuve: 'Procédure + photos local.',
    ref: 'RA Standard 2020 v1.3, §10.5.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-PR-10',
    cat: 'qualite_securite',
    titre: 'Laboratoires accrédités ISO 17025',
    desc: 'Analyses confiées à laboratoires accrédités ISO 17025.',
    crit: 'majeure',
    preuve: 'Bulletins avec accréditation.',
    ref: 'RA Standard 2020 v1.3, §10.5.5 + ISO 17025',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CHAPITRE 11 — DOCUMENTATION (15 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'RA-DOC-01',
    cat: 'documentation',
    titre: 'Manuel RA complet et à jour',
    desc: 'Manuel système couvrant les 11 chapitres du standard, daté, signé par direction. Mise à jour annuelle.',
    crit: 'majeure',
    preuve: 'Manuel daté.',
    ref: 'RA Standard 2020 v1.3, Chapitre 11 §11.1',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-02',
    cat: 'documentation',
    titre: 'Procédures opératoires (SOP) écrites',
    desc: 'SOP par activité critique : achats, traçabilité, formations, lutte intégrée, gestion non-conformité, audit interne.',
    crit: 'majeure',
    preuve: 'Bibliothèque SOP versionnée.',
    ref: 'RA Standard 2020 v1.3, §11.1.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-03',
    cat: 'documentation',
    titre: 'Registres opérationnels accessibles',
    desc: 'Registres RA (transactions, formations, NC, applications pesticides) facilement accessibles aux auditeurs.',
    crit: 'majeure',
    preuve: 'Démonstration accès rapide.',
    ref: 'RA Standard 2020 v1.3, §11.1.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-04',
    cat: 'documentation',
    titre: 'Plan formation annuel pour tous les niveaux',
    desc: 'Plan formation : producteurs, opérateurs, managers. Sujets : RA, sécurité, environnement, qualité, droits humains.',
    crit: 'majeure',
    preuve: 'Plan formation + budget.',
    ref: 'RA Standard 2020 v1.3, §11.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-05',
    cat: 'documentation',
    titre: 'Registre formations dispensées',
    desc: 'Registre détaillé : date, formateur, contenu, participants, attestations.',
    crit: 'majeure',
    preuve: 'Registre formations.',
    ref: 'RA Standard 2020 v1.3, §11.2.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-06',
    cat: 'documentation',
    titre: 'Communication aux producteurs (bulletins, AG)',
    desc: 'Bulletin périodique aux producteurs membres : prix RA, projets, formations, alertes. Format adapté.',
    crit: 'mineure',
    preuve: 'Échantillons communications.',
    ref: 'RA Standard 2020 v1.3, §11.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-07',
    cat: 'documentation',
    titre: 'Affichage public informations clés',
    desc: 'Affichage permanent : politique durabilité, charte droits humains, anti-corruption, contact plaintes, contact RA.',
    crit: 'mineure',
    preuve: 'Photos affichage.',
    ref: 'RA Standard 2020 v1.3, §11.3.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-08',
    cat: 'documentation',
    titre: 'Documents bilingues français/malagasy',
    desc: 'Documents clés (politiques, chartes, plans) disponibles français ET malagasy.',
    crit: 'mineure',
    preuve: 'Spécimens bilingues.',
    ref: 'RA Standard 2020 v1.3, §11.3.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-09',
    cat: 'documentation',
    titre: 'Indicateurs de performance suivis',
    desc: 'KPI : volumes RA, prime versée, formations dispensées, NC traitées, accidents travail. Tableau de bord trimestriel.',
    crit: 'mineure',
    preuve: 'Tableau de bord KPI.',
    ref: 'RA Standard 2020 v1.3, §11.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-10',
    cat: 'documentation',
    titre: 'Conservation registres minimum 5 ans',
    desc: 'Tous registres RA conservés ≥ 5 ans après dernière inscription.',
    crit: 'majeure',
    preuve: 'Politique archivage.',
    ref: 'RA Standard 2020 v1.3, §11.5',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-11',
    cat: 'documentation',
    titre: 'Sauvegarde numérique des registres',
    desc: 'Backup numérique régulier des registres clés. Protection contre perte (incendie, inondation, vol).',
    crit: 'mineure',
    preuve: 'Procédure backup + cloud sync.',
    ref: 'RA Standard 2020 v1.3, §11.5.2',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-12',
    cat: 'documentation',
    titre: 'Plan d\'audit interne RA',
    desc: 'Plan annuel audit interne : périmètre, dates, auditeurs, méthodologie. Avant audit externe.',
    crit: 'majeure',
    preuve: 'Plan audit interne.',
    ref: 'RA Standard 2020 v1.3, §11.6',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-13',
    cat: 'documentation',
    titre: 'Rapport audit interne avec écarts',
    desc: 'Rapport audit interne identifie écarts (NC majeures, mineures, observations). Plan d\'actions associé.',
    crit: 'majeure',
    preuve: 'Rapport audit interne signé.',
    ref: 'RA Standard 2020 v1.3, §11.6.3',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-14',
    cat: 'documentation',
    titre: 'Suivi mise en œuvre actions correctives',
    desc: 'Pour chaque NC identifiée : plan d\'action daté, responsable, vérification efficacité.',
    crit: 'majeure',
    preuve: 'Registre NC avec suivi.',
    ref: 'RA Standard 2020 v1.3, §11.6.4',
    auto: 0, regle: null,
  },
  {
    code: 'RA-DOC-15',
    cat: 'documentation',
    titre: 'Engagement public sur les résultats',
    desc: 'Publication annuelle synthèse résultats RA : volumes certifiés, projets prime, indicateurs sociaux/environnementaux.',
    crit: 'recommandation',
    preuve: 'Rapport annuel publié (site web ou print).',
    ref: 'RA Standard 2020 v1.3, §11.7',
    auto: 0, regle: null,
  },
];

// ============================================================
// SEED IDEMPOTENT
// ============================================================

export const seedCertifTrackRainforest = () => {
  const ref = db.getFirstSync(
    'SELECT id FROM referentiels WHERE code = ?',
    [REF_CODE]
  );
  if (!ref) {
    console.log(`⚠ Référentiel ${REF_CODE} introuvable, seed Rainforest annulé`);
    return;
  }

  const existingCount = db.getFirstSync(
    'SELECT COUNT(*) as nb FROM exigences_referentiel WHERE referentiel_id = ?',
    [ref.id]
  );

  // Cible : 3 démo + 137 = 140
  if (existingCount.nb >= 140) {
    console.log(`✅ Seed Rainforest déjà complet (${existingCount.nb} exigences)`);
    return;
  }

  console.log(`🌱 Seed Rainforest Session 8d — ${EXIGENCES_RA.length} exigences à insérer...`);

  let insere = 0;
  let skip = 0;
  let ordre = 100;

  EXIGENCES_RA.forEach((ex) => {
    const existing = db.getFirstSync(
      'SELECT id FROM exigences_referentiel WHERE referentiel_id = ? AND code_exigence = ?',
      [ref.id, ex.code]
    );
    if (existing) { skip++; return; }

    db.runSync(
      `INSERT INTO exigences_referentiel (
        referentiel_id, code_exigence, categorie, titre, description,
        criticite, preuve_attendue, reference_officielle,
        auto_verifiable, regle_auto_code, ordre
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        ref.id, ex.code, ex.cat, ex.titre, ex.desc,
        ex.crit, ex.preuve, ex.ref,
        ex.auto || 0, ex.regle || null, ordre++,
      ]
    );
    insere++;
  });

  if (skip > 0) console.log(`  ↪ ${skip} exigences déjà présentes`);
  const final = db.getFirstSync(
    'SELECT COUNT(*) as nb FROM exigences_referentiel WHERE referentiel_id = ?',
    [ref.id]
  );
  console.log(`✅ Seed Rainforest complet : ${final.nb} exigences en base (${insere} nouvelles)`);
};