// database/certifTrackFairtrade.js
// Session 8c — Fairtrade FLO complet
// 107 exigences supplémentaires (en plus des 3 démo Session 8)
// Total après seed : 110 exigences Fairtrade
//
// Sources de référence :
//   - Fairtrade Standard for Small-scale Producer Organizations (SPO) v2.5 (2024)
//   - Fairtrade Trader Standard (pour les opérateurs comme AgriSuite Madagascar)
//   - Fairtrade Hired Labour Standard (si main-d'œuvre salariée importante)
//   - Critères produit : Coffee, Cocoa, Vanilla, Spices, Fresh Fruits
//
// Périmètre : organisation de petits producteurs Madagascar + opérateur exportateur
//
// ⚠️ Validation finale par FLOCERT (auditeur exclusif Fairtrade) avant audit réel.

import * as SQLite from 'expo-sqlite';

const db = SQLite.openDatabaseSync('agrisuite.db');

const REF_CODE = 'FAIRTRADE_FLO';

// ============================================================
// CATALOGUE EXIGENCES FAIRTRADE — 107 entrées
// ============================================================

const EXIGENCES_FAIRTRADE = [

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 1 : GOUVERNANCE DÉMOCRATIQUE (15 exigences hors 2 démo)
  // ════════════════════════════════════════════════════════════
  {
    code: 'FT-GOUV-02',
    cat: 'gouvernance',
    titre: 'Statuts juridiques officiels enregistrés',
    desc: 'Organisation de producteurs enregistrée légalement à Madagascar (coopérative, association, GIE) avec statuts conformes au droit national.',
    crit: 'majeure',
    preuve: 'Copie statuts enregistrés + récépissé administration.',
    ref: 'Fairtrade SPO Standard 2024, §1.1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-03',
    cat: 'gouvernance',
    titre: 'Conseil d\'administration élu démocratiquement',
    desc: 'CA composé de membres élus par l\'assemblée générale au suffrage universel (1 producteur = 1 voix), mandats limités dans le temps, renouvellement régulier.',
    crit: 'majeure',
    preuve: 'PV élections CA + liste élus avec dates de mandat.',
    ref: 'Fairtrade SPO Standard 2024, §1.2.1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-04',
    cat: 'gouvernance',
    titre: 'Quorum AG respecté (≥ 50% membres présents ou représentés)',
    desc: 'Pour validité des décisions AG : minimum 50% des membres présents physiquement ou par procuration. Quorum vérifié par signature feuille de présence.',
    crit: 'majeure',
    preuve: 'Feuilles de présence AG + calcul quorum dans PV.',
    ref: 'Fairtrade SPO Standard 2024, §1.2.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-05',
    cat: 'gouvernance',
    titre: 'Représentation équitable des femmes au CA',
    desc: 'Politique active d\'inclusion des femmes : objectif minimum 30% de femmes au CA. Plan d\'action si pourcentage inférieur.',
    crit: 'mineure',
    preuve: 'Liste membres CA avec genre + plan d\'action genre.',
    ref: 'Fairtrade SPO Standard 2024, §1.2.4 (genre)',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-06',
    cat: 'gouvernance',
    titre: 'Comité Fairtrade (Premium Committee) constitué',
    desc: 'Comité dédié à la gestion de la prime Fairtrade, distinct du CA si possible. Composition représentative (genre, zones, types producteurs). Mandat écrit.',
    crit: 'majeure',
    preuve: 'PV constitution comité + mandat signé + liste membres.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-07',
    cat: 'gouvernance',
    titre: 'Règlement intérieur de l\'organisation',
    desc: 'Règlement intérieur écrit définissant : conditions d\'adhésion, droits/devoirs membres, fonctionnement organes, procédures vote, gestion conflits, sanctions.',
    crit: 'majeure',
    preuve: 'Document règlement intérieur signé par CA et adopté en AG.',
    ref: 'Fairtrade SPO Standard 2024, §1.1.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-08',
    cat: 'gouvernance',
    titre: 'Politique anti-corruption documentée',
    desc: 'Charte anti-corruption signée par direction et CA : interdiction pots-de-vin, transparence appels d\'offres, séparation pouvoirs, dénonciation protégée.',
    crit: 'majeure',
    preuve: 'Document charte anti-corruption + signatures + diffusion personnel.',
    ref: 'Fairtrade SPO Standard 2024, §1.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-09',
    cat: 'gouvernance',
    titre: 'Liste des membres (producteurs) à jour',
    desc: 'Registre exhaustif des producteurs membres avec : identité, parcelles, surfaces, productions, date d\'adhésion. Mise à jour annuelle minimum.',
    crit: 'majeure',
    preuve: 'Registre membres consultable + dernière mise à jour < 12 mois.',
    ref: 'Fairtrade SPO Standard 2024, §1.1.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-10',
    cat: 'gouvernance',
    titre: 'Formation des dirigeants à la gouvernance',
    desc: 'Membres CA et comité Fairtrade formés annuellement : gestion coopérative, comptabilité, droits Fairtrade, leadership. Formations dispensées par organismes reconnus.',
    crit: 'mineure',
    preuve: 'Plan de formation annuel + attestations formations.',
    ref: 'Fairtrade SPO Standard 2024, §1.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-11',
    cat: 'gouvernance',
    titre: 'Procédure de gestion des conflits internes',
    desc: 'Procédure écrite : commission de médiation, recours en AG, escalade externe possible. Tracé des conflits et résolutions.',
    crit: 'mineure',
    preuve: 'Procédure écrite + registre des conflits traités.',
    ref: 'Fairtrade SPO Standard 2024, §1.2.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-12',
    cat: 'gouvernance',
    titre: 'Bilan annuel d\'activité présenté en AG',
    desc: 'Présentation annuelle en AG : activités, productions, ventes Fairtrade vs conventionnel, prime utilisée, projets réalisés. Documents distribués aux membres.',
    crit: 'majeure',
    preuve: 'Rapport annuel d\'activité + PV AG validation.',
    ref: 'Fairtrade SPO Standard 2024, §1.2.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-13',
    cat: 'gouvernance',
    titre: 'Comptes annuels audités et approuvés',
    desc: 'Comptes annuels audités par expert-comptable indépendant, présentés et approuvés en AG. Conservation minimum 5 ans.',
    crit: 'majeure',
    preuve: 'Rapport audit comptable < 12 mois + PV approbation AG.',
    ref: 'Fairtrade SPO Standard 2024, §1.4.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-14',
    cat: 'gouvernance',
    titre: 'Politique de transparence financière',
    desc: 'Tout membre peut accéder aux comptes, contrats commerciaux, salaires direction, sur demande raisonnable. Affichage public des décisions financières clés.',
    crit: 'mineure',
    preuve: 'Politique transparence écrite + procédure d\'accès aux documents.',
    ref: 'Fairtrade SPO Standard 2024, §1.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-15',
    cat: 'gouvernance',
    titre: 'Représentation équitable des zones géographiques',
    desc: 'Si organisation couvre plusieurs zones (Côte Est, Sambirano), CA reflète diversité géographique. Évite la centralisation du pouvoir sur une zone.',
    crit: 'mineure',
    preuve: 'Cartographie des membres + composition CA par zone.',
    ref: 'Fairtrade SPO Standard 2024, §1.2.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-GOUV-16',
    cat: 'gouvernance',
    titre: 'Plan stratégique pluriannuel',
    desc: 'Document de planification 3-5 ans : objectifs production, expansion membres, investissements, formations. Validé en AG, révisé annuellement.',
    crit: 'recommandation',
    preuve: 'Document plan stratégique daté + révisions annuelles.',
    ref: 'Fairtrade SPO Standard 2024, §1.3',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 2 : PRIME FAIRTRADE (12 exigences hors 1 démo)
  // ════════════════════════════════════════════════════════════
  {
    code: 'FT-PRIME-02',
    cat: 'gouvernance',
    titre: 'Prix minimum Fairtrade payé aux producteurs',
    desc: 'Pour chaque achat Fairtrade : prix minimum garanti par le standard produit (Coffee Min Price, Cocoa Min Price, Vanilla Min Price). Si prix marché supérieur, prix marché s\'applique.',
    crit: 'majeure',
    preuve: 'Bons d\'achat producteurs avec prix versé ≥ prix minimum Fairtrade officiel.',
    ref: 'Fairtrade Pricing Database 2024 + Trader Standard §3.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-03',
    cat: 'gouvernance',
    titre: 'Plan d\'utilisation annuel de la prime voté en AG',
    desc: 'Avant chaque exercice, plan d\'utilisation détaillé de la prime soumis au vote AG. Catégories : développement social, productivité, environnement, qualité, paiement direct.',
    crit: 'majeure',
    preuve: 'PV AG approuvant le plan annuel + budget détaillé prime.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-04',
    cat: 'gouvernance',
    titre: 'Compte bancaire séparé pour la prime',
    desc: 'Prime versée sur compte bancaire dédié, distinct des comptes opérationnels. Aucun mélange avec trésorerie générale.',
    crit: 'majeure',
    preuve: 'Relevés du compte prime + IBAN dédié.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-05',
    cat: 'gouvernance',
    titre: 'Comptabilité analytique de la prime',
    desc: 'Comptabilité distincte : entrées (par lot vendu Fairtrade), dépenses (par projet ligne par ligne), solde mensuel. Réconciliation avec relevés bancaires.',
    crit: 'majeure',
    preuve: 'Plan comptable analytique prime + livre comptable.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-06',
    cat: 'gouvernance',
    titre: 'Justificatifs de dépenses prime conservés',
    desc: 'Pour chaque dépense de prime : facture, devis, bon de livraison, paiement bancaire conservés. Archivage 5 ans minimum.',
    crit: 'majeure',
    preuve: 'Dossier justificatifs par projet financé.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-07',
    cat: 'gouvernance',
    titre: 'Maximum 20% prime en paiement direct producteurs',
    desc: 'Si distribution directe aux producteurs (cash payment), maximum 20% du montant total prime/an. Le reste pour projets collectifs.',
    crit: 'majeure',
    preuve: 'Bilan annuel prime montrant répartition projets collectifs / paiement direct.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.6',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-08',
    cat: 'gouvernance',
    titre: 'Évaluation d\'impact des projets prime',
    desc: 'Pour chaque projet financé > 1000 EUR : évaluation d\'impact à 12 mois (bénéficiaires, résultats, leçons). Présentée en AG.',
    crit: 'mineure',
    preuve: 'Rapports d\'évaluation de projets.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.7',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-09',
    cat: 'gouvernance',
    titre: 'Communication aux membres sur l\'usage prime',
    desc: 'Information régulière (bulletins, panneaux d\'affichage, AG) sur les projets en cours et résultats. Photos et témoignages encouragés.',
    crit: 'mineure',
    preuve: 'Échantillons communications internes.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-10',
    cat: 'gouvernance',
    titre: 'Solde de prime non consommé reporté',
    desc: 'Si solde non consommé en fin d\'exercice, report sur exercice suivant avec décision documentée. Pas de réaffectation hors prime.',
    crit: 'majeure',
    preuve: 'Bilan annuel prime + PV décision report.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.6',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-11',
    cat: 'gouvernance',
    titre: 'Pas d\'utilisation prime pour fonctionnement courant',
    desc: 'Interdiction d\'utiliser la prime pour salaires permanents, loyers bureaux, frais de fonctionnement courants. Prime = investissement collectif.',
    crit: 'majeure',
    preuve: 'Comptabilité analytique montrant catégories d\'usage.',
    ref: 'Fairtrade SPO Standard 2024, §2.1.6',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-12',
    cat: 'gouvernance',
    titre: 'Versement prime sous 30 jours après réception acheteur',
    desc: 'L\'opérateur reverse la prime à l\'organisation de producteurs sous 30 jours après réception du paiement de l\'acheteur. Délai contractualisé.',
    crit: 'majeure',
    preuve: 'Contrats commerciaux + relevés bancaires montrant délais.',
    ref: 'Fairtrade Trader Standard 2024, §3.5.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-PRIME-13',
    cat: 'gouvernance',
    titre: 'Prime Fairtrade Premium par produit appliquée',
    desc: 'Montant prime conforme à la grille Fairtrade par produit (ex. café Arabica : 0,20 USD/lb ; cacao : 240 USD/t ; vanille : 0,50 USD/kg). Vérifier grille en vigueur année.',
    crit: 'majeure',
    preuve: 'Calculs de prime par lot vendu cohérents avec grille FLO.',
    ref: 'Fairtrade Pricing Database (mise à jour annuelle)',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 3 : SOCIAL & TRAVAIL (15 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'FT-SOC-01',
    cat: 'social_travail',
    titre: 'Aucun travail forcé ou en servitude',
    desc: 'Tous les travailleurs (membres et salariés) sont libres. Aucune retention de papiers d\'identité, aucune dette servant à attacher au travail.',
    crit: 'majeure',
    preuve: 'Charte interne + entretiens aléatoires lors d\'audit.',
    ref: 'Fairtrade SPO Standard 2024, §3.1 + ILO C29/C105',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-02',
    cat: 'social_travail',
    titre: 'Aucun travail des enfants < 15 ans',
    desc: 'Travail des enfants < 15 ans interdit. Aide familiale légère acceptée hors heures scolaires, sans entrave à la scolarité.',
    crit: 'majeure',
    preuve: 'Registre personnel avec dates de naissance + politique anti-travail enfants.',
    ref: 'Fairtrade SPO Standard 2024, §3.2 + ILO C138',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-03',
    cat: 'social_travail',
    titre: 'Pas de travail dangereux pour les 15-18 ans',
    desc: 'Jeunes travailleurs entre 15 et 18 ans : interdiction des travaux dangereux (manipulation produits, machines lourdes, hauteurs, charges lourdes).',
    crit: 'majeure',
    preuve: 'Liste des travaux dangereux interdits + registre personnel jeunes.',
    ref: 'Fairtrade SPO Standard 2024, §3.2 + ILO C182',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-04',
    cat: 'social_travail',
    titre: 'Liberté syndicale et négociation collective',
    desc: 'Droits de constituer ou rejoindre librement un syndicat. Aucune sanction pour activité syndicale. Si convention collective applicable, respect.',
    crit: 'majeure',
    preuve: 'Politique liberté syndicale + absence litiges.',
    ref: 'Fairtrade SPO Standard 2024, §3.4 + ILO C87/C98',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-05',
    cat: 'social_travail',
    titre: 'Salaires conformes au minimum légal ou conventionnel',
    desc: 'Salaires versés ≥ SMIG malgache ou minimum conventionnel le plus élevé. Bulletins de paie remis. Engagement vers le salaire vital (« Living Wage ») à terme.',
    crit: 'majeure',
    preuve: 'Bulletins de paie + référence SMIG.',
    ref: 'Fairtrade SPO Standard 2024, §3.5 + Hired Labour Standard',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-06',
    cat: 'social_travail',
    titre: 'Heures de travail conformes (max 48h/semaine)',
    desc: 'Durée légale respectée : 40h normales / 48h max avec heures sup. Repos hebdomadaire 24h continues. Heures sup volontaires et majorées (+25% à +50%).',
    crit: 'majeure',
    preuve: 'Registre des heures + paie heures supplémentaires.',
    ref: 'Fairtrade SPO Standard 2024, §3.5 + ILO C1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-07',
    cat: 'social_travail',
    titre: 'Congés payés et jours fériés respectés',
    desc: 'Congés annuels payés conformes au droit malgache (minimum 30 jours/an pour permanents). Jours fériés payés.',
    crit: 'majeure',
    preuve: 'Registre des congés + bulletins paie.',
    ref: 'Fairtrade SPO Standard 2024, §3.5 + Code du travail malgache',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-08',
    cat: 'social_travail',
    titre: 'Contrats écrits pour tous les salariés permanents',
    desc: 'Tout salarié permanent dispose d\'un contrat écrit signé spécifiant : poste, salaire, horaires, congés, conditions de rupture.',
    crit: 'majeure',
    preuve: 'Échantillon de contrats.',
    ref: 'Fairtrade SPO Standard 2024, §3.5 + Code du travail',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-09',
    cat: 'social_travail',
    titre: 'Sécurité sociale (CNAPS) cotisations à jour',
    desc: 'Tous les salariés permanents inscrits à la CNAPS (Caisse Nationale de Prévoyance Sociale Madagascar). Cotisations patronales et salariales versées.',
    crit: 'majeure',
    preuve: 'Quittances de cotisation CNAPS < 3 mois.',
    ref: 'Fairtrade SPO Standard 2024 + Code travail malgache',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-10',
    cat: 'social_travail',
    titre: 'Aucune discrimination embauche/conditions',
    desc: 'Politique anti-discrimination : genre, origine ethnique, religion, orientation, handicap, âge, opinion politique. Recrutement basé sur compétences.',
    crit: 'majeure',
    preuve: 'Charte anti-discrimination + statistiques effectifs (diversité).',
    ref: 'Fairtrade SPO Standard 2024, §3.6 + ILO C100/C111',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-11',
    cat: 'social_travail',
    titre: 'Sécurité au travail : EPI fournis et utilisés',
    desc: 'EPI adaptés (gants, masques, lunettes, bottes, casques) fournis gratuitement par employeur. Formation à l\'usage. Renouvelés selon usure.',
    crit: 'majeure',
    preuve: 'Registre remise EPI + photos terrain.',
    ref: 'Fairtrade SPO Standard 2024, §3.5.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-12',
    cat: 'social_travail',
    titre: 'Politique anti-harcèlement (sexuel et moral)',
    desc: 'Politique écrite + procédure de signalement confidentielle + sanctions. Formation des managers. Sensibilisation tout personnel annuellement.',
    crit: 'majeure',
    preuve: 'Document politique + registre formations + registre signalements (anonymisé).',
    ref: 'Fairtrade SPO Standard 2024, §3.7',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-13',
    cat: 'social_travail',
    titre: 'Logement décent si fourni par employeur',
    desc: 'Si l\'employeur fournit logement aux saisonniers : conformité aux normes (eau potable, électricité, sanitaires, espace minimum, sécurité incendie).',
    crit: 'majeure',
    preuve: 'Photos logements + checklist conformité.',
    ref: 'Fairtrade Hired Labour Standard 2024, §3.5.6',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-14',
    cat: 'social_travail',
    titre: 'Égalité salariale femmes/hommes pour travail égal',
    desc: 'À poste et compétences égales, salaire égal entre femmes et hommes. Audit interne salarial recommandé.',
    crit: 'majeure',
    preuve: 'Grille salariale + audit interne salaires (si réalisé).',
    ref: 'Fairtrade SPO Standard 2024, §3.6 + ILO C100',
    auto: 0, regle: null,
  },
  {
    code: 'FT-SOC-15',
    cat: 'social_travail',
    titre: 'Procédure de licenciement encadrée et juste',
    desc: 'Licenciement uniquement pour motif sérieux (faute, économique). Procédure : avertissement écrit, entretien, préavis selon ancienneté, indemnité légale.',
    crit: 'mineure',
    preuve: 'Procédure écrite + dossiers de licenciement (anonymisés).',
    ref: 'Fairtrade SPO Standard 2024, §3.5.4',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 4 : ENVIRONNEMENT (15 exigences hors 1 démo)
  // ════════════════════════════════════════════════════════════
  {
    code: 'FT-ENV-02',
    cat: 'environnement',
    titre: 'Liste des pesticides interdits (Fairtrade Prohibited Materials List)',
    desc: 'Aucun pesticide listé dans la Fairtrade Prohibited Materials List (mise à jour 2024) utilisé. Liste plus large que Codex.',
    crit: 'majeure',
    preuve: 'Inventaire intrants + comparaison liste FPML.',
    ref: 'Fairtrade Prohibited Materials List 2024',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-03',
    cat: 'environnement',
    titre: 'Plan de réduction usage pesticides',
    desc: 'Plan documenté visant la réduction progressive des pesticides : alternatives biologiques, lutte intégrée, surveillance ravageurs. Objectifs quantifiés.',
    crit: 'mineure',
    preuve: 'Plan de réduction + indicateurs annuels.',
    ref: 'Fairtrade SPO Standard 2024, §4.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-04',
    cat: 'environnement',
    titre: 'Pas de défrichement de forêt primaire',
    desc: 'Aucun défrichement de forêt primaire ou écosystème naturel pour étendre les plantations après date d\'engagement Fairtrade.',
    crit: 'majeure',
    preuve: 'Cartographie historique + déclarations producteurs.',
    ref: 'Fairtrade SPO Standard 2024, §4.1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-05',
    cat: 'environnement',
    titre: 'Préservation zones protégées',
    desc: 'Identification des aires protégées (parcs, réserves) à proximité. Aucune activité agricole dans ces zones. Zone tampon respectée.',
    crit: 'majeure',
    preuve: 'Cartographie aires protégées + plan parcellaire.',
    ref: 'Fairtrade SPO Standard 2024, §4.1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-06',
    cat: 'environnement',
    titre: 'Conservation des sols',
    desc: 'Pratiques anti-érosion (couvert végétal, courbes de niveau, paillage), restitution matière organique, analyses sol périodiques.',
    crit: 'mineure',
    preuve: 'Plan de conservation des sols + analyses MO.',
    ref: 'Fairtrade SPO Standard 2024, §4.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-07',
    cat: 'environnement',
    titre: 'Gestion responsable de l\'eau',
    desc: 'Plan de gestion eau : sources identifiées, prélèvements mesurés si possible, irrigation économe (goutte-à-goutte préféré), pas de pollution des cours d\'eau.',
    crit: 'majeure',
    preuve: 'Plan gestion eau + photos systèmes irrigation.',
    ref: 'Fairtrade SPO Standard 2024, §4.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-08',
    cat: 'environnement',
    titre: 'Bandes tampons le long des cours d\'eau',
    desc: 'Bandes enherbées ou boisées de minimum 5m le long des cours d\'eau. Aucun épandage à moins de 10m des points d\'eau.',
    crit: 'majeure',
    preuve: 'Plan parcellaire + photos bandes tampons.',
    ref: 'Fairtrade SPO Standard 2024, §4.4.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-09',
    cat: 'environnement',
    titre: 'Aucun OGM utilisé',
    desc: 'Interdiction absolue OGM (semences, plants, intrants). Vigilance sur soja, maïs si rotation. Attestations fournisseurs.',
    crit: 'majeure',
    preuve: 'Attestations sans OGM des fournisseurs.',
    ref: 'Fairtrade SPO Standard 2024, §4.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-10',
    cat: 'environnement',
    titre: 'Réduction émissions gaz à effet de serre',
    desc: 'Mesures de réduction GES : agroforesterie (séquestration carbone), énergies renouvelables, efficacité énergétique, transport optimisé.',
    crit: 'mineure',
    preuve: 'Plan d\'actions GES + calcul empreinte carbone si réalisé.',
    ref: 'Fairtrade SPO Standard 2024, §4.6 (climat)',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-11',
    cat: 'environnement',
    titre: 'Plan d\'adaptation au changement climatique',
    desc: 'Identification des risques climatiques (sécheresse, cyclones MDG, érosion) et plan d\'adaptation : variétés résilientes, agroforesterie, gestion eau.',
    crit: 'mineure',
    preuve: 'Plan d\'adaptation climatique signé.',
    ref: 'Fairtrade SPO Standard 2024, §4.6.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-12',
    cat: 'environnement',
    titre: 'Tri sélectif et collecte déchets dangereux',
    desc: 'Tri systématique : organiques (compost), recyclables, ordures ménagères. Déchets dangereux (emballages pesticides, batteries) collectés séparément, filière agréée.',
    crit: 'majeure',
    preuve: 'Plan tri + photos zones tri + contrats collecteurs.',
    ref: 'Fairtrade SPO Standard 2024, §4.7',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-13',
    cat: 'environnement',
    titre: 'Aucun brûlage de déchets non autorisé',
    desc: 'Brûlage à l\'air libre interdit (sauf végétaux secs en zones rurales si autorisé). Aucun brûlage de plastiques, batteries, chiffons souillés.',
    crit: 'majeure',
    preuve: 'Politique gestion déchets + photos.',
    ref: 'Fairtrade SPO Standard 2024, §4.7',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-14',
    cat: 'environnement',
    titre: 'Préservation biodiversité (espèces locales)',
    desc: 'Maintien d\'arbres indigènes, haies, mares, zones non cultivées (≥ 5% SAU). Plantation d\'espèces locales préférées aux exotiques.',
    crit: 'mineure',
    preuve: 'Cartographie zones biodiversité + inventaire espèces.',
    ref: 'Fairtrade SPO Standard 2024, §4.1.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-15',
    cat: 'environnement',
    titre: 'Choix variétal adapté au terroir',
    desc: 'Variétés locales ou rustiques préférées aux variétés exigeantes en intrants. Catalogue variétal documenté par culture.',
    crit: 'recommandation',
    preuve: 'Liste des variétés cultivées avec justification.',
    ref: 'Fairtrade SPO Standard 2024, §4.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-ENV-16',
    cat: 'environnement',
    titre: 'Plan de prévention pollution accidentelle',
    desc: 'Procédures en cas de déversement (pesticides, hydrocarbures) : confinement, absorbants, élimination. Stockages avec rétention.',
    crit: 'mineure',
    preuve: 'Procédure prévention pollution + photos rétentions.',
    ref: 'Fairtrade SPO Standard 2024, §4.4.5',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 5 : TRAÇABILITÉ (15 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'FT-TRAC-01',
    cat: 'tracabilite',
    titre: 'Code FLOID attribué et utilisé',
    desc: 'Organisation enregistrée chez FLOCERT avec FLOID unique. FLOID mentionné sur tous documents commerciaux Fairtrade (factures, BL, contrats).',
    crit: 'majeure',
    preuve: 'Certificat FLOCERT + factures avec FLOID.',
    ref: 'Fairtrade Trader Standard 2024, §3.1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-02',
    cat: 'tracabilite',
    titre: 'Identification claire des produits Fairtrade',
    desc: 'Tous les lots Fairtrade clairement identifiés (étiquette, code lot avec préfixe FT- ou identifiant). Distinction visuelle avec produits conventionnels.',
    crit: 'majeure',
    preuve: 'Plan de marquage + photos lots.',
    ref: 'Fairtrade Trader Standard 2024, §3.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-03',
    cat: 'tracabilite',
    titre: 'Séparation physique Fairtrade / non-Fairtrade',
    desc: 'Lors stockage et transformation, séparation physique des lots Fairtrade et conventionnels. Si mêmes équipements, plages horaires distinctes.',
    crit: 'majeure',
    preuve: 'Plan d\'unité + procédure séparation.',
    ref: 'Fairtrade Trader Standard 2024, §3.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-04',
    cat: 'tracabilite',
    titre: 'Contrats commerciaux mentionnant Fairtrade',
    desc: 'Contrats avec acheteurs précisent : produit Fairtrade, prix minimum + prime, FLOID, volume, qualité, modalités de paiement et de versement prime.',
    crit: 'majeure',
    preuve: 'Contrats signés avec mentions Fairtrade.',
    ref: 'Fairtrade Trader Standard 2024, §3.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-05',
    cat: 'tracabilite',
    titre: 'Bilan matière annuel Fairtrade',
    desc: 'Annuellement : volumes achetés Fairtrade aux producteurs vs volumes vendus en Fairtrade vs stocks. Aucun écart inexpliqué.',
    crit: 'majeure',
    preuve: 'Bilan matière annuel signé.',
    ref: 'Fairtrade Trader Standard 2024, §3.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-06',
    cat: 'tracabilite',
    titre: 'Aucun substitution Fairtrade / conventionnel',
    desc: 'Interdit de vendre comme Fairtrade un volume supérieur à ce qui a été acheté Fairtrade. Volumes vendus FT ≤ volumes achetés FT.',
    crit: 'majeure',
    preuve: 'Bilan matière démontrant équilibre.',
    ref: 'Fairtrade Trader Standard 2024, §3.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-07',
    cat: 'tracabilite',
    titre: 'Reporting trimestriel à FLOCERT',
    desc: 'Reporting trimestriel ou annuel à FLOCERT via plateforme FLOCERT eCert : volumes, prix, primes versées. Délais respectés.',
    crit: 'majeure',
    preuve: 'Captures d\'écran reporting eCert + accusés.',
    ref: 'Fairtrade Trader Standard 2024, §3.6',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-08',
    cat: 'tracabilite',
    titre: 'Lots composites Fairtrade tracés',
    desc: 'Si lots composites, tous les lots parents Fairtrade. Mélange Fairtrade/conventionnel interdit.',
    crit: 'majeure',
    preuve: 'Vérification automatique sur lots composites.',
    ref: 'Fairtrade Trader Standard 2024, §3.3',
    auto: 1, regle: 'MELANGE_BIO_CONV',
  },
  {
    code: 'FT-TRAC-09',
    cat: 'tracabilite',
    titre: 'Logo Fairtrade conforme charte graphique',
    desc: 'Si logo Fairtrade utilisé sur emballages : conforme aux règles d\'usage (taille, couleur, position) édictées par Fairtrade International.',
    crit: 'mineure',
    preuve: 'Spécimens emballages + validation par Fairtrade Marketing.',
    ref: 'Fairtrade Mark Use Guidelines',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-10',
    cat: 'tracabilite',
    titre: 'Numéro de licence Fairtrade Mark obtenu',
    desc: 'Si commercialisation grand public sous logo Fairtrade : licence Fairtrade Mark obtenue auprès de Fairtrade Madagascar ou international.',
    crit: 'majeure',
    preuve: 'Contrat de licence Fairtrade Mark.',
    ref: 'Fairtrade Mark Use Guidelines',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-11',
    cat: 'tracabilite',
    titre: 'Conservation registres 5 ans minimum',
    desc: 'Tous les registres Fairtrade (achats, ventes, primes, contrats, AG) conservés au minimum 5 ans après dernière inscription.',
    crit: 'majeure',
    preuve: 'Politique archivage + démonstration accès registres anciens.',
    ref: 'Fairtrade SPO Standard 2024, §1.4.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-12',
    cat: 'tracabilite',
    titre: 'Audit FLOCERT annuel passé',
    desc: 'Audit physique annuel par FLOCERT (ou auditeur mandaté). Suivi des recommandations et levée des non-conformités dans délais.',
    crit: 'majeure',
    preuve: 'Rapport audit FLOCERT < 12 mois + plan actions correctives.',
    ref: 'Fairtrade Standard Compliance Criteria',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-13',
    cat: 'tracabilite',
    titre: 'Test de traçabilité simulé annuel',
    desc: 'Une fois par an, simulation : choisir 1 lot vendu Fairtrade, retracer en moins de 4h jusqu\'aux producteurs initiaux. Documenter exercice.',
    crit: 'mineure',
    preuve: 'Rapport test traçabilité.',
    ref: 'Fairtrade Trader Standard 2024, §3.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-14',
    cat: 'tracabilite',
    titre: 'Achats à des producteurs membres uniquement',
    desc: 'Pour qu\'un volume soit vendable Fairtrade, il doit avoir été acheté à un producteur membre certifié de l\'organisation. Liste des fournisseurs Fairtrade limitée aux membres.',
    crit: 'majeure',
    preuve: 'Liste fournisseurs FT = liste membres + bons d\'achat.',
    ref: 'Fairtrade SPO Standard 2024, §1.1.5 + Trader Standard',
    auto: 0, regle: null,
  },
  {
    code: 'FT-TRAC-15',
    cat: 'tracabilite',
    titre: 'Exigences majeures justifiées par preuve',
    desc: 'Pour chaque exigence majeure Fairtrade, au moins une preuve enregistrée dans CertifTrack.',
    crit: 'majeure',
    preuve: 'Vérification automatique par moteur de conformité.',
    ref: 'Fairtrade Standard Compliance Criteria',
    auto: 1, regle: 'PREUVE_MANQUANTE_MAJEURE',
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 6 : DOCUMENTATION (10 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'FT-DOC-01',
    cat: 'documentation',
    titre: 'Manuel de l\'organisation Fairtrade',
    desc: 'Manuel décrivant : structure, gouvernance, procédures clés, gestion prime, formation, gestion conflits. Validé par CA, accessible aux membres.',
    crit: 'majeure',
    preuve: 'Manuel daté, signé, version à jour.',
    ref: 'Fairtrade SPO Standard 2024, §1.4.1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-DOC-02',
    cat: 'documentation',
    titre: 'Procédures opératoires écrites',
    desc: 'Procédures par activité critique : adhésion membres, achats, gestion prime, traçabilité, audit interne, gestion non-conformité.',
    crit: 'majeure',
    preuve: 'Bibliothèque procédures versionnée.',
    ref: 'Fairtrade SPO Standard 2024, §1.4.1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-DOC-03',
    cat: 'documentation',
    titre: 'Registre des formations dispensées aux membres',
    desc: 'Registre chronologique : formations Fairtrade (gouvernance, qualité, environnement, social), participants, formateurs, contenus, attestations.',
    crit: 'majeure',
    preuve: 'Registre formations.',
    ref: 'Fairtrade SPO Standard 2024, §1.3 + 4.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-DOC-04',
    cat: 'documentation',
    titre: 'Affichage public des informations clés',
    desc: 'Affichage permanent dans les locaux : prix Fairtrade en vigueur, montant prime, statuts, charte anti-corruption, point contact FLOCERT.',
    crit: 'mineure',
    preuve: 'Photos affichage.',
    ref: 'Fairtrade SPO Standard 2024, §1.4.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-DOC-05',
    cat: 'documentation',
    titre: 'Procès-verbaux AG et CA archivés',
    desc: 'PV de toutes AG et réunions CA datés, signés, archivés. Mentionnent ordre du jour, participants, décisions prises (avec votes), actions futures.',
    crit: 'majeure',
    preuve: 'Classeurs PV signés.',
    ref: 'Fairtrade SPO Standard 2024, §1.2.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-DOC-06',
    cat: 'documentation',
    titre: 'Documents traduits en langue locale',
    desc: 'Documents clés (statuts, règlement, charte, plan prime) disponibles en français ET malagasy pour accessibilité de tous les membres.',
    crit: 'mineure',
    preuve: 'Spécimens documents bilingues.',
    ref: 'Fairtrade SPO Standard 2024, §1.4.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-DOC-07',
    cat: 'documentation',
    titre: 'Contrats avec partenaires écrits et signés',
    desc: 'Tous les contrats commerciaux, prestations, services formalisés par écrit et signés par parties. Clauses Fairtrade lorsque applicables.',
    crit: 'majeure',
    preuve: 'Échantillon de contrats.',
    ref: 'Fairtrade SPO Standard 2024, §1.4.1',
    auto: 0, regle: null,
  },
  {
    code: 'FT-DOC-08',
    cat: 'documentation',
    titre: 'Plan d\'audit interne annuel',
    desc: 'Audit interne avant audit FLOCERT pour identifier les écarts. Rapport, plan d\'actions, suivi.',
    crit: 'mineure',
    preuve: 'Rapport audit interne < 12 mois.',
    ref: 'Fairtrade SPO Standard 2024, §1.4.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-DOC-09',
    cat: 'documentation',
    titre: 'Politique de confidentialité données membres',
    desc: 'Données personnelles des membres protégées : accès limité, pas de partage non autorisé. Conformité protection données.',
    crit: 'mineure',
    preuve: 'Politique confidentialité écrite.',
    ref: 'Fairtrade SPO Standard 2024, §1.4',
    auto: 0, regle: null,
  },
  {
    code: 'FT-DOC-10',
    cat: 'documentation',
    titre: 'Communication transparente avec membres',
    desc: 'Bulletin périodique (mensuel ou trimestriel) aux membres : prix marchés, projets prime, formations, AG. Format adapté (papier, SMS, radio communautaire).',
    crit: 'recommandation',
    preuve: 'Échantillons communications.',
    ref: 'Fairtrade SPO Standard 2024, §1.4.4',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 7 : INTRANTS & PRATIQUES (10 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'FT-INT-01',
    cat: 'intrants',
    titre: 'Liste pesticides interdits Fairtrade respectée',
    desc: 'Conformité avec Fairtrade Prohibited Materials List 2024 (plus large que Codex et UE) : interdiction Paraquat, Glyphosate, Atrazine, et 200+ autres substances.',
    crit: 'majeure',
    preuve: 'Inventaire intrants vérifié contre FPML.',
    ref: 'Fairtrade Hazardous Materials List 2024',
    auto: 0, regle: null,
  },
  {
    code: 'FT-INT-02',
    cat: 'intrants',
    titre: 'Stockage sécurisé des pesticides',
    desc: 'Local dédié, fermé à clé, ventilé, sol étanche, pictogrammes danger, EPI à proximité. Stockage séparé des semences et nourriture.',
    crit: 'majeure',
    preuve: 'Photos local + plan + procédure d\'accès.',
    ref: 'Fairtrade SPO Standard 2024, §3.5.5 + 4.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-INT-03',
    cat: 'intrants',
    titre: 'Formation à l\'usage sécuritaire pesticides',
    desc: 'Tout opérateur appliquant des pesticides est formé annuellement : usage EPI, dosage, signes intoxication, premiers secours, élimination emballages.',
    crit: 'majeure',
    preuve: 'Attestations formation < 12 mois.',
    ref: 'Fairtrade SPO Standard 2024, §3.5.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-INT-04',
    cat: 'intrants',
    titre: 'Délais avant récolte (DAR) respectés',
    desc: 'Si pesticides utilisés (autorisés Fairtrade), DAR du fabricant strictement respecté avant récolte. Registre des applications.',
    crit: 'majeure',
    preuve: 'Registre application avec DAR + dates récolte.',
    ref: 'Fairtrade SPO Standard 2024, §4.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-INT-05',
    cat: 'intrants',
    titre: 'Engrais conformes aux règles Fairtrade',
    desc: 'Engrais autorisés : organiques (compost, fumier), minéraux naturels. Engrais de synthèse limités selon culture. Pas d\'engrais issus de boues STEP.',
    crit: 'majeure',
    preuve: 'Liste engrais utilisés + factures.',
    ref: 'Fairtrade SPO Standard 2024, §4.3.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-INT-06',
    cat: 'intrants',
    titre: 'Semences non OGM',
    desc: 'Toutes semences/plants utilisés sont non-OGM. Attestations fournisseurs pour cultures à risque (maïs, soja, coton).',
    crit: 'majeure',
    preuve: 'Attestations fournisseurs sans OGM.',
    ref: 'Fairtrade SPO Standard 2024, §4.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-INT-07',
    cat: 'intrants',
    titre: 'Préférence semences locales et adaptées',
    desc: 'Semences locales, traditionnelles ou rustiques préférées. Documentation des choix variétaux.',
    crit: 'recommandation',
    preuve: 'Liste variétés + justification.',
    ref: 'Fairtrade SPO Standard 2024, §4.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-INT-08',
    cat: 'pratiques_culturales',
    titre: 'Lutte intégrée préventive',
    desc: 'Mesures préventives prioritaires : variétés résistantes, rotation, auxiliaires, observation. Traitement curatif en dernier recours.',
    crit: 'mineure',
    preuve: 'Plan de protection intégrée par culture.',
    ref: 'Fairtrade SPO Standard 2024, §4.3.3',
    auto: 0, regle: null,
  },
  {
    code: 'FT-INT-09',
    cat: 'pratiques_culturales',
    titre: 'Rotation des cultures (annuelles)',
    desc: 'Pour cultures annuelles, rotation pluriannuelle incluant légumineuses ou couverts. Évite épuisement sol et pression maladies.',
    crit: 'mineure',
    preuve: 'Plan de rotation par parcelle.',
    ref: 'Fairtrade SPO Standard 2024, §4.2',
    auto: 0, regle: null,
  },
  {
    code: 'FT-INT-10',
    cat: 'pratiques_culturales',
    titre: 'Agroforesterie pour cultures pérennes',
    desc: 'Cacao, café, vanille en système agroforestier (ombrage, biodiversité). Pas de monoculture en plein soleil.',
    crit: 'mineure',
    preuve: 'Plan parcellaire + inventaire ombrage.',
    ref: 'Fairtrade SPO Standard 2024, §4.1.3',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 8 : QUALITÉ (10 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'FT-QUAL-01',
    cat: 'qualite_securite',
    titre: 'Critères de qualité par produit définis',
    desc: 'Cahier des charges qualité par produit : caractéristiques visuelles, taux humidité, taux défauts, paramètres physico-chimiques, organoleptique.',
    crit: 'majeure',
    preuve: 'Cahier des charges qualité signé.',
    ref: 'Fairtrade Product Standards 2024',
    auto: 0, regle: null,
  },
  {
    code: 'FT-QUAL-02',
    cat: 'qualite_securite',
    titre: 'Contrôle qualité à l\'achat aux producteurs',
    desc: 'Lors achat aux producteurs membres : contrôle qualité systématique selon critères. Refus possible avec motif. Traçabilité contrôles.',
    crit: 'majeure',
    preuve: 'Bons d\'achat avec contrôle qualité tracé.',
    ref: 'Fairtrade SPO Standard 2024, §1.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-QUAL-03',
    cat: 'qualite_securite',
    titre: 'Analyses contaminants conformes UE',
    desc: 'Pour export UE : analyses conformes Règlement (UE) 2023/915 (mycotoxines, métaux, pesticides). Bulletins par lot ou campagne.',
    crit: 'majeure',
    preuve: 'Bulletins d\'analyse.',
    ref: 'Règlement (UE) 2023/915 + Fairtrade Product Standards',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'FT-QUAL-04',
    cat: 'qualite_securite',
    titre: 'Plan d\'amélioration qualité continu',
    desc: 'Plan annuel d\'amélioration qualité : objectifs chiffrés, formations producteurs, équipements, suivi indicateurs.',
    crit: 'mineure',
    preuve: 'Plan amélioration qualité + indicateurs.',
    ref: 'Fairtrade SPO Standard 2024, §1.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-QUAL-05',
    cat: 'qualite_securite',
    titre: 'Échantillonnage représentatif des lots',
    desc: 'Procédure d\'échantillonnage statistiquement représentative pour analyses qualité. Plusieurs prélèvements par lot, mélange et envoi labo.',
    crit: 'mineure',
    preuve: 'Procédure échantillonnage écrite.',
    ref: 'Bonnes pratiques Codex + Fairtrade Product Standards',
    auto: 0, regle: null,
  },
  {
    code: 'FT-QUAL-06',
    cat: 'qualite_securite',
    titre: 'Étape post-récolte documentée',
    desc: 'Tous les lots clôturés ont au moins une étape post-récolte documentée (séchage, tri, fermentation selon produit).',
    crit: 'majeure',
    preuve: 'Étapes ExportTrack pour chaque lot.',
    ref: 'Fairtrade Product Standards + bonnes pratiques HACCP',
    auto: 1, regle: 'ETAPE_MANQUANTE',
  },
  {
    code: 'FT-QUAL-07',
    cat: 'qualite_securite',
    titre: 'Laboratoires d\'analyse accrédités',
    desc: 'Analyses confiées à laboratoires accrédités ISO 17025 (CTHT Tamatave, IPM, Eurofins, etc.). Rapports avec n° accréditation.',
    crit: 'majeure',
    preuve: 'Bulletins analyse mentionnant accréditation.',
    ref: 'ISO 17025 + Fairtrade Product Standards',
    auto: 0, regle: null,
  },
  {
    code: 'FT-QUAL-08',
    cat: 'qualite_securite',
    titre: 'Procédure non-conformité qualité',
    desc: 'Si lot non conforme : retrait, enquête, action corrective, notification client si déjà expédié. Tracé.',
    crit: 'majeure',
    preuve: 'Procédure écrite + registre NC qualité.',
    ref: 'Fairtrade Trader Standard 2024, §3.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-QUAL-09',
    cat: 'qualite_securite',
    titre: 'Échantillothèque conservée',
    desc: 'Échantillons représentatifs conservés ≥ 6 mois après expédition. Permet contre-analyses en cas de contestation client.',
    crit: 'mineure',
    preuve: 'Procédure échantillothèque + photos local.',
    ref: 'Fairtrade Trader Standard 2024, §3.5',
    auto: 0, regle: null,
  },
  {
    code: 'FT-QUAL-10',
    cat: 'qualite_securite',
    titre: 'Spécifications acheteur respectées',
    desc: 'Pour chaque acheteur, spécifications produit (taux défauts, calibre, taux humidité) respectées et tracées. Documents qualité par expédition.',
    crit: 'majeure',
    preuve: 'Bulletins qualité par expédition signés.',
    ref: 'Fairtrade Trader Standard 2024, §3.4',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 9 : POST-RÉCOLTE (5 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'FT-POSTREC-01',
    cat: 'gestion_post_recolte',
    titre: 'Locaux post-récolte propres et adaptés',
    desc: 'Locaux séchage, tri, stockage propres, ventilés, protégés des nuisibles. Plan de nettoyage périodique.',
    crit: 'majeure',
    preuve: 'Photos locaux + plan nettoyage.',
    ref: 'Fairtrade Product Standards + bonnes pratiques HACCP',
    auto: 0, regle: null,
  },
  {
    code: 'FT-POSTREC-02',
    cat: 'gestion_post_recolte',
    titre: 'Séparation Fairtrade / non-Fairtrade en stockage',
    desc: 'Lots Fairtrade physiquement séparés des conventionnels en stockage (zones distinctes ou plages temporelles).',
    crit: 'majeure',
    preuve: 'Plan stockage + procédure.',
    ref: 'Fairtrade Trader Standard 2024, §3.3',
    auto: 1, regle: 'MELANGE_BIO_CONV',
  },
  {
    code: 'FT-POSTREC-03',
    cat: 'gestion_post_recolte',
    titre: 'Conditionnement avec emballages adaptés',
    desc: 'Emballages adaptés au produit (sacs jute café/cacao, cartons épices) et au transport (résistance, protection humidité).',
    crit: 'mineure',
    preuve: 'Spécifications emballages + factures.',
    ref: 'Fairtrade Product Standards 2024',
    auto: 0, regle: null,
  },
  {
    code: 'FT-POSTREC-04',
    cat: 'gestion_post_recolte',
    titre: 'Pas de fumigation chimique non autorisée',
    desc: 'Fumigation au phosphure d\'hydrogène (PH3) ou bromure de méthyle interdite sauf dérogation et étiquetage explicite acheteur.',
    crit: 'majeure',
    preuve: 'Politique fumigation + déclaration sur l\'honneur.',
    ref: 'Fairtrade Product Standards + UE',
    auto: 0, regle: null,
  },
  {
    code: 'FT-POSTREC-05',
    cat: 'gestion_post_recolte',
    titre: 'Lutte nuisibles sans produits interdits',
    desc: 'Lutte nuisibles avec moyens autorisés Fairtrade (pièges, ultrasons, terre de diatomée). Pas de pesticides interdits.',
    crit: 'majeure',
    preuve: 'Plan lutte nuisibles + liste produits.',
    ref: 'Fairtrade SPO Standard 2024, §4.3 + 4.7',
    auto: 0, regle: null,
  },
];

// ============================================================
// SEED IDEMPOTENT
// ============================================================

export const seedCertifTrackFairtrade = () => {
  const ref = db.getFirstSync(
    'SELECT id FROM referentiels WHERE code = ?',
    [REF_CODE]
  );
  if (!ref) {
    console.log(`⚠ Référentiel ${REF_CODE} introuvable, seed Fairtrade annulé`);
    return;
  }

  const existingCount = db.getFirstSync(
    'SELECT COUNT(*) as nb FROM exigences_referentiel WHERE referentiel_id = ?',
    [ref.id]
  );

  // Cible : 3 démo + 107 = 110
  if (existingCount.nb >= 110) {
    console.log(`✅ Seed Fairtrade déjà complet (${existingCount.nb} exigences)`);
    return;
  }

  console.log(`🌱 Seed Fairtrade Session 8c — ${EXIGENCES_FAIRTRADE.length} exigences à insérer...`);

  let insere = 0;
  let skip = 0;
  let ordre = 100;

  EXIGENCES_FAIRTRADE.forEach((ex) => {
    const existing = db.getFirstSync(
      'SELECT id FROM exigences_referentiel WHERE referentiel_id = ? AND code_exigence = ?',
      [ref.id, ex.code]
    );
    if (existing) { skip++; return; }

    db.runSync(
      `INSERT INTO exigences_referentiel (
        referentiel_id, code_exigence, categorie, titre, description,
        criticite, preuve_attendue, reference_officielle,
        auto_verifiable, regle_auto_code, ordre
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        ref.id, ex.code, ex.cat, ex.titre, ex.desc,
        ex.crit, ex.preuve, ex.ref,
        ex.auto || 0, ex.regle || null, ordre++,
      ]
    );
    insere++;
  });

  if (skip > 0) console.log(`  ↪ ${skip} exigences déjà présentes`);
  const final = db.getFirstSync(
    'SELECT COUNT(*) as nb FROM exigences_referentiel WHERE referentiel_id = ?',
    [ref.id]
  );
  console.log(`✅ Seed Fairtrade complet : ${final.nb} exigences en base (${insere} nouvelles)`);
};