// database/certifTrackBioUe.js
// Session 8a — BIO UE 2018/848 complet
// 117 exigences supplémentaires (en plus des 3 démo Session 8)
// Total après seed : 120 exigences BIO UE
//
// Sources de référence :
//   - Règlement (UE) 2018/848 du 30 mai 2018 (production biologique et étiquetage)
//   - Règlement d'exécution (UE) 2021/1165 (substances autorisées)
//   - Règlement délégué (UE) 2020/2146 (règles dérogatoires)
//   - Règlement délégué (UE) 2021/1006 (règles agriculture/aquaculture)
//
// Couvre : annuelles (24m conversion) + pérennes (36m conversion)
// Périmètre cultures : gingembre, vanille, girofle, café, cacao, poivre, cannelle, litchi
//
// ⚠️ Note : modélisation basée sur lecture du règlement EUR-Lex.
// Validation finale à faire par un consultant Ecocert avant audit réel.

import * as SQLite from 'expo-sqlite';

const db = SQLite.openDatabaseSync('agrisuite.db');

// Code référentiel cible
const REF_CODE = 'BIO_UE';

// ============================================================
// CATALOGUE EXIGENCES BIO UE — 117 entrées
// ============================================================

const EXIGENCES_BIO_UE = [

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 1 : TRAÇABILITÉ (15 exigences, hors 1 démo)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-TRAC-02',
    cat: 'tracabilite',
    titre: 'Identification visuelle des parcelles BIO',
    desc: 'Les parcelles en agriculture biologique ou en conversion doivent être identifiées sur le terrain (panneaux, balises, marquages) et différenciées des parcelles conventionnelles voisines.',
    crit: 'mineure',
    preuve: 'Photos panneaux/balises sur parcelles, plan parcellaire avec identification BIO/conversion/conventionnel.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.7.5',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-03',
    cat: 'tracabilite',
    titre: 'Plan parcellaire à jour avec coordonnées GPS',
    desc: 'Plan complet de toutes les parcelles de l\'exploitation avec coordonnées GPS, superficie exacte, culture en place, statut BIO/conversion/conventionnel. Mis à jour annuellement.',
    crit: 'majeure',
    preuve: 'Document plan parcellaire daté, signé, avec coordonnées GPS de chaque parcelle. Disponible via AgroMap.',
    ref: 'Règlement (UE) 2018/848, Article 39 §1(d) + Annexe II',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-04',
    cat: 'tracabilite',
    titre: 'Registre des cultures avec dates clés',
    desc: 'Registre tenu à jour avec : variété semée, date de semis/plantation, date de récolte, quantités récoltées, parcelle d\'origine. Conservation 5 ans minimum.',
    crit: 'majeure',
    preuve: 'Registre des cultures consultable, par exemple via MaraîcherGuide (cultures en cours et récoltes).',
    ref: 'Règlement (UE) 2018/848, Article 39 §1(d)',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-05',
    cat: 'tracabilite',
    titre: 'Code de lot unique par production homogène',
    desc: 'Chaque lot de production doit porter un identifiant unique non réutilisable (format MDG-AAAA-XXX-CCC-NNN). Aucun mélange entre lots sans traçabilité ascendante.',
    crit: 'majeure',
    preuve: 'Lot enregistré dans ExportTrack avec code unique conforme au format défini.',
    ref: 'Règlement (UE) 2018/848, Article 30 §6',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-06',
    cat: 'tracabilite',
    titre: 'Traçabilité ascendante du lot fini au producteur',
    desc: 'Pour tout lot expédié, possibilité de remonter à 100% : producteur(s), parcelle(s), date(s) de récolte, intrants utilisés, étapes post-récolte, analyses qualité.',
    crit: 'majeure',
    preuve: 'Test de traçabilité simulé annuel : sélectionner 1 lot et reconstituer toute sa chaîne. Documenter l\'exercice.',
    ref: 'Règlement (UE) 2018/848, Article 30 §6 + Annexe III',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-07',
    cat: 'tracabilite',
    titre: 'Traçabilité descendante du producteur au client',
    desc: 'Pour tout lot vendu, possibilité de savoir quel client / quel pays / quelle date d\'expédition. Permet le rappel produit en cas de non-conformité détectée a posteriori.',
    crit: 'majeure',
    preuve: 'Liste des expéditions avec lot, acheteur, date, n° BL, port de destination.',
    ref: 'Règlement (UE) 2018/848, Article 30 §6',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-08',
    cat: 'tracabilite',
    titre: 'Test de rappel produit annuel',
    desc: 'Simulation annuelle d\'un rappel produit avec délai cible < 4 heures pour identifier tous les lots concernés. Documenté avec rapport.',
    crit: 'mineure',
    preuve: 'Rapport de test de rappel annuel signé, mentionnant délai réalisé, lots identifiés, points d\'amélioration.',
    ref: 'Règlement (UE) 2018/848, Article 39 + bonnes pratiques HACCP',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-09',
    cat: 'tracabilite',
    titre: 'Lots composites tracés vers parents',
    desc: 'Tout lot composite (préfixe C dans le code) doit conserver la liste exhaustive de ses lots parents avec quantités. Tous les lots parents doivent partager le même statut BIO.',
    crit: 'majeure',
    preuve: 'Lot composite enregistré avec liste des lots parents et quantités. Vérification automatique du statut BIO de chaque parent.',
    ref: 'Règlement (UE) 2018/848, Article 30 + Annexe III',
    auto: 1, regle: 'MELANGE_BIO_CONV',
  },
  {
    code: 'BIO-TRAC-10',
    cat: 'tracabilite',
    titre: 'Numéro d\'opérateur certifié visible sur étiquette',
    desc: 'L\'étiquetage des produits BIO export doit mentionner le code de l\'organisme certificateur (ex. FR-BIO-01) et le n° d\'opérateur attribué.',
    crit: 'majeure',
    preuve: 'Spécimen d\'étiquette du lot avec code certificateur + n° opérateur visible.',
    ref: 'Règlement (UE) 2018/848, Article 33 §1',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-11',
    cat: 'tracabilite',
    titre: 'Logo BIO européen présent et conforme',
    desc: 'Le logo Eurofeuille doit être apposé sur les produits BIO préemballés destinés à l\'UE, avec mention du pays d\'origine (« Agriculture Madagascar » ou « Agriculture non UE »).',
    crit: 'majeure',
    preuve: 'Spécimen d\'emballage final avec Eurofeuille + mention origine conforme.',
    ref: 'Règlement (UE) 2018/848, Article 33 §3 + Annexe V',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-12',
    cat: 'tracabilite',
    titre: 'Interdiction du logo BIO en période de conversion',
    desc: 'Aucune mention BIO ni logo Eurofeuille n\'est autorisé sur les lots issus de cultures encore en période de conversion (avant fin du délai 24/36 mois).',
    crit: 'majeure',
    preuve: 'Vérification automatique : si engagement BIO statut "en_conversion", alerte sur étiquetage.',
    ref: 'Règlement (UE) 2018/848, Article 30 §3',
    auto: 1, regle: 'DELAI_CONVERSION_BIO',
  },
  {
    code: 'BIO-TRAC-13',
    cat: 'tracabilite',
    titre: 'Mention « produit en conversion » obligatoire',
    desc: 'Pour les produits issus de cultures pérennes en 2ème ou 3ème année de conversion (mais avant la 36ème), mention obligatoire « produit en conversion vers l\'agriculture biologique ».',
    crit: 'mineure',
    preuve: 'Étiquetage spécifique conversion sur les lots concernés.',
    ref: 'Règlement (UE) 2018/848, Article 30 §3',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-14',
    cat: 'tracabilite',
    titre: 'Registre des ventes avec lots associés',
    desc: 'Pour chaque vente : date, acheteur, quantité, code(s) lot(s), facture. Permet la réconciliation entre production et ventes BIO.',
    crit: 'majeure',
    preuve: 'Registre des ventes ou export comptable mentionnant les lots BIO vendus.',
    ref: 'Règlement (UE) 2018/848, Article 39 §1(d)',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-15',
    cat: 'tracabilite',
    titre: 'Bilan matière annuel cohérent',
    desc: 'Annuellement, calcul du bilan : entrées (semences/plants/intrants) + production - ventes - pertes = stocks. Aucun écart inexpliqué supérieur à 5%.',
    crit: 'majeure',
    preuve: 'Document bilan matière annuel signé, daté, avec calcul détaillé.',
    ref: 'Règlement (UE) 2018/848, Article 39 §1(d) + Article 35',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-TRAC-16',
    cat: 'tracabilite',
    titre: 'Conservation des registres pendant 5 ans minimum',
    desc: 'Tous les registres BIO (parcellaire, intrants, cultures, lots, analyses, ventes) doivent être conservés pendant 5 ans minimum après la dernière inscription.',
    crit: 'majeure',
    preuve: 'Confirmation écrite (charte interne) que les registres sont archivés 5 ans.',
    ref: 'Règlement (UE) 2018/848, Article 39 §1(d)',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 2 : INTRANTS (18 exigences, hors 1 démo)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-INT-02',
    cat: 'intrants',
    titre: 'Semences et plants issus de l\'agriculture biologique',
    desc: 'Utilisation prioritaire de semences et matériel de reproduction végétale BIO. Dérogation possible si indisponibilité documentée auprès de l\'organisme certificateur.',
    crit: 'majeure',
    preuve: 'Factures d\'achat semences avec mention BIO, ou dérogation écrite de l\'organisme certificateur.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.8.5',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-03',
    cat: 'intrants',
    titre: 'Aucun OGM utilisé',
    desc: 'Aucun organisme génétiquement modifié (OGM), produit dérivé d\'OGM ou produit obtenu par OGM ne peut être utilisé en production BIO. Vigilance particulière sur soja, maïs, coton.',
    crit: 'majeure',
    preuve: 'Attestation fournisseur sans OGM pour chaque intrant à risque, ou choix de variétés notoirement non-GM.',
    ref: 'Règlement (UE) 2018/848, Article 11',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-04',
    cat: 'intrants',
    titre: 'Engrais et amendements conformes Annexe I 2021/1165',
    desc: 'Seuls les engrais, amendements et produits fertilisants listés à l\'Annexe I du règlement 2021/1165 sont autorisés (compost, fumier, vinasse, phosphate naturel, etc.).',
    crit: 'majeure',
    preuve: 'Liste exhaustive des intrants utilisés avec fiche technique. Cohérence avec Annexe I 2021/1165.',
    ref: 'Règlement d\'exécution (UE) 2021/1165, Annexe I',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-05',
    cat: 'intrants',
    titre: 'Produits phytosanitaires conformes Annexe II 2021/1165',
    desc: 'Seuls les produits de protection des cultures listés à l\'Annexe II du règlement 2021/1165 sont autorisés (cuivre, soufre, Bacillus thuringiensis, neem, pyrèthre, etc.).',
    crit: 'majeure',
    preuve: 'Liste des produits phyto utilisés + factures + fiches techniques. Cohérence avec Annexe II 2021/1165.',
    ref: 'Règlement d\'exécution (UE) 2021/1165, Annexe II',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-06',
    cat: 'intrants',
    titre: 'Aucun engrais minéral azoté de synthèse',
    desc: 'Interdiction absolue de l\'urée, ammonitrate, sulfate d\'ammoniaque, et tout engrais azoté de synthèse. La fertilisation azotée passe par fumier, compost, légumineuses.',
    crit: 'majeure',
    preuve: 'Registre des fertilisants montrant exclusivement des sources organiques ou minérales naturelles.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.9.6',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-07',
    cat: 'intrants',
    titre: 'Stockage séparé des intrants BIO et non-BIO',
    desc: 'Si l\'exploitation gère aussi du conventionnel, les intrants BIO (semences, fertilisants autorisés) doivent être stockés dans une zone distincte clairement identifiée.',
    crit: 'mineure',
    preuve: 'Photos zones de stockage distinctes, plan d\'unité avec marquage BIO.',
    ref: 'Règlement (UE) 2018/848, Article 9 §11',
    auve: null, regle: null,
  },
  {
    code: 'BIO-INT-08',
    cat: 'intrants',
    titre: 'Origine biologique des plants pérennes',
    desc: 'Pour vanille, girofle, café, cacao, poivre, cannelle, litchi : les jeunes plants utilisés en plantation initiale doivent être issus de pépinières BIO ou en conversion. Dérogation à demander à l\'organisme certificateur si indisponibilité.',
    crit: 'majeure',
    preuve: 'Factures pépinière avec mention BIO, ou dérogation écrite, ou attestation production interne BIO.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.8',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-09',
    cat: 'intrants',
    titre: 'Aucun désherbant chimique de synthèse',
    desc: 'Glyphosate, paraquat, atrazine et tout désherbant de synthèse sont strictement interdits. Le désherbage est mécanique, manuel, thermique, ou par paillage/couverture du sol.',
    crit: 'majeure',
    preuve: 'Registre des opérations culturales mentionnant uniquement des méthodes mécaniques/manuelles. Aucune trace de désherbant chimique en stock.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.10',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-10',
    cat: 'intrants',
    titre: 'Substances de nettoyage/désinfection autorisées',
    desc: 'Pour le nettoyage des équipements, locaux de stockage et outils, seules les substances listées à l\'Annexe IV du 2021/1165 sont autorisées (eau, vapeur, savon, vinaigre, alcool, eau oxygénée, etc.).',
    crit: 'mineure',
    preuve: 'Liste des produits de nettoyage utilisés + fiches techniques + factures.',
    ref: 'Règlement d\'exécution (UE) 2021/1165, Annexe IV',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-11',
    cat: 'intrants',
    titre: 'Compost issu de matières premières autorisées',
    desc: 'Le compost utilisé doit être produit à partir de matières premières autorisées (résidus végétaux, fumier d\'élevage non industriel, déchets de cuisine sans viande). Pas de boues de STEP.',
    crit: 'majeure',
    preuve: 'Description du procédé de compostage, liste des matières premières, registre de production compost.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.9.4',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-12',
    cat: 'intrants',
    titre: 'Limite annuelle azote organique 170 kg N/ha',
    desc: 'L\'apport total d\'azote organique (fumier, compost, légumineuses) ne doit pas dépasser 170 kg d\'azote par hectare et par an, en moyenne sur l\'exploitation.',
    crit: 'mineure',
    preuve: 'Calcul annuel apport azote organique total / surface utile.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.9.6',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-13',
    cat: 'intrants',
    titre: 'Provenance fumier hors élevage industriel',
    desc: 'Si fumier acheté à l\'extérieur, il ne doit pas provenir d\'élevages industriels (cages en batterie volailles, élevages porcins en confinement strict).',
    crit: 'mineure',
    preuve: 'Origine du fumier documentée + visite ou attestation du fournisseur.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.9.3',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-14',
    cat: 'intrants',
    titre: 'Pas de chaulage avec chaux vive issue de procédés interdits',
    desc: 'Le chaulage est autorisé avec chaux d\'origine naturelle (calcaire broyé, dolomie). Interdiction des amendements calciques issus de procédés industriels non listés.',
    crit: 'mineure',
    preuve: 'Fiche technique de l\'amendement utilisé + facture.',
    ref: 'Règlement d\'exécution (UE) 2021/1165, Annexe I',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-15',
    cat: 'intrants',
    titre: 'Produits de lutte biologique correctement utilisés',
    desc: 'Si lâchers d\'auxiliaires (Trichogrammes, coccinelles), les espèces doivent être indigènes ou autorisées. Pas d\'OGM, pas d\'espèces invasives.',
    crit: 'mineure',
    preuve: 'Factures d\'achat auxiliaires + nom scientifique des espèces.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.10.2',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-16',
    cat: 'intrants',
    titre: 'Cuivre limité à 4 kg/ha/an en moyenne sur 5 ans',
    desc: 'Si utilisation de fongicides cupriques (bouillie bordelaise) sur vanille, café ou cacao, la dose totale annuelle de cuivre métal est plafonnée à 4 kg/ha en moyenne sur 5 ans.',
    crit: 'majeure',
    preuve: 'Registre annuel d\'application cuivre par parcelle, calcul moyenne 5 ans.',
    ref: 'Règlement d\'exécution (UE) 2021/1165, Annexe II',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-17',
    cat: 'intrants',
    titre: 'Aucun additif de croissance ni hormones',
    desc: 'Interdiction de toute hormone de croissance, régulateur de croissance de synthèse, ou stimulateur chimique sur les cultures.',
    crit: 'majeure',
    preuve: 'Liste exhaustive des intrants utilisés vérifiée annuellement contre les listes interdites.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.6',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-18',
    cat: 'intrants',
    titre: 'Eau d\'irrigation de qualité non contaminée',
    desc: 'L\'eau utilisée pour l\'irrigation doit être de qualité satisfaisante (analyse microbiologique et chimique recommandée). Pas d\'utilisation d\'eaux usées non traitées.',
    crit: 'mineure',
    preuve: 'Analyse eau d\'irrigation < 24 mois (E. coli, métaux lourds, pesticides) ou attestation de qualité de la source.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.5',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-INT-19',
    cat: 'intrants',
    titre: 'Pas de sols contaminés (métaux lourds, hydrocarbures)',
    desc: 'Les parcelles BIO doivent être exemptes de contamination significative des sols. Analyse de sol initiale recommandée si terrain à historique douteux (industrie, ancien dépôt).',
    crit: 'majeure',
    preuve: 'Analyse de sol initiale (Pb, Cd, As, hydrocarbures) si contexte à risque.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.7',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 3 : PRATIQUES CULTURALES (12 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-PRAT-01',
    cat: 'pratiques_culturales',
    titre: 'Rotation des cultures annuelles',
    desc: 'Pour les cultures annuelles (gingembre, légumes), rotation pluriannuelle obligatoire incluant au moins une culture de légumineuses ou un engrais vert. Aucune monoculture.',
    crit: 'majeure',
    preuve: 'Plan de rotation pluriannuel par parcelle. Registre des cultures précédentes.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.9.2',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-02',
    cat: 'pratiques_culturales',
    titre: 'Couverture du sol entre cultures',
    desc: 'Limitation des sols nus : couverture par engrais verts, paillage, mulch, ou cultures de couverture entre deux cycles annuels.',
    crit: 'mineure',
    preuve: 'Photos parcelles entre cycles + registre opérations culturales.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.9.1',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-03',
    cat: 'pratiques_culturales',
    titre: 'Gestion des adventices sans herbicide',
    desc: 'Désherbage exclusivement mécanique (sarclage, binage), manuel, thermique (flammes), ou par paillage/films biodégradables. Aucun herbicide chimique.',
    crit: 'majeure',
    preuve: 'Registre opérations culturales mentionnant les méthodes utilisées. Photos chantiers de désherbage.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.10.1',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-04',
    cat: 'pratiques_culturales',
    titre: 'Lutte intégrée préventive contre ravageurs',
    desc: 'Mise en place de mesures préventives : variétés résistantes, pratiques culturales adéquates, présence d\'auxiliaires (haies, fleurs mellifères), rotation. Le traitement curatif est en dernier recours.',
    crit: 'mineure',
    preuve: 'Plan de protection intégrée par culture + observations terrain.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.10.2',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-05',
    cat: 'pratiques_culturales',
    titre: 'Densité de plantation respectée pour pérennes',
    desc: 'Pour vanille, café, cacao, poivre : respect des densités de plantation préconisées par les itinéraires techniques BIO (espacement suffisant pour aération, biodiversité).',
    crit: 'mineure',
    preuve: 'Plan de plantation avec densité par hectare. Comparaison avec ITK CropEngine.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.7',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-06',
    cat: 'pratiques_culturales',
    titre: 'Tuteurage vivant pour vanille (Gliricidia, Erythrina)',
    desc: 'Pour la vanille, le tuteur vivant doit être une espèce ligneuse adaptée et entretenue (tailles régulières pour gestion ombrage). Tuteurs morts à éviter.',
    crit: 'mineure',
    preuve: 'Photos parcelles vanille avec tuteurs vivants identifiés. Registre de taille.',
    ref: 'Cahier ITK vanille BIO Madagascar + Annexe II 2018/848',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-07',
    cat: 'pratiques_culturales',
    titre: 'Ombrage adapté pour café et cacao',
    desc: 'Pour café et cacao, plantation sous ombrage diversifié (arbres fruitiers, légumineuses, ligneux indigènes). Pas de monoculture en plein soleil.',
    crit: 'mineure',
    preuve: 'Plan de la parcelle agroforestière + inventaire des espèces d\'ombrage.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.9 + bonnes pratiques tropicales',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-08',
    cat: 'pratiques_culturales',
    titre: 'Choix variétal adapté aux conditions locales',
    desc: 'Privilégier variétés rustiques, locales ou adaptées au climat malgache. Documentation du choix variétal pour chaque culture.',
    crit: 'recommandation',
    preuve: 'Note technique justifiant le choix des variétés plantées.',
    ref: 'Règlement (UE) 2018/848, Article 6 §a',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-09',
    cat: 'pratiques_culturales',
    titre: 'Récolte au stade de maturité optimal',
    desc: 'Récolte effectuée au stade physiologique optimal pour qualité maximale (vanille à maturité, gousses fendillées ; café à maturité rouge ; cacao à maturité physiologique).',
    crit: 'mineure',
    preuve: 'Critères de maturité documentés par culture + photos récolte.',
    ref: 'Bonnes pratiques agricoles + ITK BIO',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-10',
    cat: 'pratiques_culturales',
    titre: 'Pas de brûlis comme pratique culturale',
    desc: 'Le brûlis (écobuage, défrichage par feu) est interdit comme pratique culturale courante en BIO. Exceptions pour gestion d\'ennemis spécifiques avec déclaration préalable.',
    crit: 'majeure',
    preuve: 'Déclaration sur l\'honneur absence de brûlis. Photos parcelles sans traces de feu récent.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.7',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-11',
    cat: 'pratiques_culturales',
    titre: 'Préservation matière organique du sol',
    desc: 'Pratiques favorisant l\'augmentation ou le maintien de la matière organique : compostage, paillage, couverts végétaux, restitution de résidus de récolte.',
    crit: 'mineure',
    preuve: 'Plan de fertilisation organique + analyses MO du sol périodiques (tous les 3-5 ans).',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.9.1',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PRAT-12',
    cat: 'pratiques_culturales',
    titre: 'Travail du sol limité (érosion, biologie)',
    desc: 'Préférer travail du sol superficiel ou semi-direct pour préserver structure et vie du sol. Sur pentes (Site D bas-fond exclu), techniques anti-érosion obligatoires.',
    crit: 'mineure',
    preuve: 'Description des pratiques de travail du sol par parcelle.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie I §1.9.1',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 4 : GESTION POST-RÉCOLTE (15 exigences, hors 1 démo)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-POSTREC-02',
    cat: 'gestion_post_recolte',
    titre: 'Récipients de récolte propres et identifiés',
    desc: 'Caisses, sacs et récipients utilisés pour la récolte BIO doivent être propres, en bon état, et identifiés (étiquette ou marquage BIO). Pas de récipients ayant contenu des produits chimiques.',
    crit: 'mineure',
    preuve: 'Photos des récipients utilisés + procédure de nettoyage.',
    ref: 'Règlement (UE) 2018/848, Article 28',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-03',
    cat: 'gestion_post_recolte',
    titre: 'Tri qualité avec critères documentés',
    desc: 'Le tri post-récolte sépare les qualités (commerciale, déchets, écarts) selon des critères écrits par culture. Lots clairement identifiés après tri.',
    crit: 'mineure',
    preuve: 'Critères de tri par culture + registre des opérations de tri (étapes ExportTrack).',
    ref: 'Règlement (UE) 2018/848, Article 28 + bonnes pratiques',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-04',
    cat: 'gestion_post_recolte',
    titre: 'Séchage solaire ou mécanique sans contamination',
    desc: 'Si séchage solaire : surface propre, à l\'abri des animaux et poussières. Si séchage mécanique : combustible non contaminant (gaz, bois propre, électricité). Pas de séchage au gasoil direct.',
    crit: 'majeure',
    preuve: 'Description du procédé de séchage par culture + photos installation.',
    ref: 'Règlement (UE) 2018/848, Article 28 + Annexe II Partie IV',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-05',
    cat: 'gestion_post_recolte',
    titre: 'Procédé de fermentation cacao documenté',
    desc: 'Si production cacao : procédé de fermentation (caisses ou tas) documenté avec durée, retournements, contrôle température. Méthode reproductible.',
    crit: 'majeure',
    preuve: 'Protocole de fermentation cacao écrit + registre relevés température/durée.',
    ref: 'Règlement (UE) 2018/848, Article 28',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-06',
    cat: 'gestion_post_recolte',
    titre: 'Préparation vanille noire/black avec scaldage',
    desc: 'Pour vanille noire prête : protocole scaldage (eau chaude 60-65°C, 3 min) + sudation + séchage solaire + affinage. Procédé documenté.',
    crit: 'majeure',
    preuve: 'Protocole de préparation vanille écrit + registre relevés (durée, température).',
    ref: 'Cahier des charges vanille MDG + Annexe II 2018/848',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-07',
    cat: 'gestion_post_recolte',
    titre: 'Stockage à l\'abri humidité, lumière, nuisibles',
    desc: 'Local de stockage propre, sec (HR < 65%), à l\'ombre, équipé contre rongeurs et insectes. Stockage sur palettes, pas à même le sol.',
    crit: 'majeure',
    preuve: 'Photos du local de stockage + relevés HR/T° périodiques + plan de lutte nuisibles.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie IV',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-08',
    cat: 'gestion_post_recolte',
    titre: 'Lutte contre nuisibles avec produits autorisés',
    desc: 'En stockage, lutte rongeurs/insectes avec moyens physiques (pièges, ultrasons), CO2, terre de diatomée. Pas de fumigation au phosphure d\'hydrogène (PH3) sans dérogation explicite.',
    crit: 'majeure',
    preuve: 'Plan de lutte nuisibles + factures produits utilisés (Annexe IV 2021/1165).',
    ref: 'Règlement d\'exécution (UE) 2021/1165, Annexe IV',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-09',
    cat: 'gestion_post_recolte',
    titre: 'Aucune fumigation chimique de synthèse',
    desc: 'Interdiction formelle de la fumigation au bromure de méthyle, au phosphure d\'hydrogène (PH3) et autres fumigants chimiques de synthèse, sauf dérogation pays-tiers et étiquetage explicite.',
    crit: 'majeure',
    preuve: 'Déclaration sur l\'honneur + registre absence de fumigation chimique. Si import requiert fumigation, lot perdu BIO.',
    ref: 'Règlement (UE) 2018/848, Annexe II + Article 28',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-10',
    cat: 'gestion_post_recolte',
    titre: 'Calibrage et conditionnement séparés du conventionnel',
    desc: 'Si l\'unité traite aussi du conventionnel : équipements dédiés OU plage horaire spécifique avec nettoyage avant. Procédure écrite.',
    crit: 'majeure',
    preuve: 'Procédure écrite séparation + registre planning machines.',
    ref: 'Règlement (UE) 2018/848, Article 28',
    auto: 1, regle: 'MELANGE_BIO_CONV',
  },
  {
    code: 'BIO-POSTREC-11',
    cat: 'gestion_post_recolte',
    titre: 'Emballages exempts de substances contaminantes',
    desc: 'Sacs, cartons, sachets : matériaux conformes contact alimentaire, sans plastifiants migrants type bisphénol A (BPA). Préférence pour emballages biodégradables ou recyclables.',
    crit: 'mineure',
    preuve: 'Fiches techniques emballages + attestation contact alimentaire fournisseur.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie IV + Règlement (UE) 2023/2006 contact alimentaire',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-12',
    cat: 'gestion_post_recolte',
    titre: 'Étiquetage conforme aux mentions obligatoires',
    desc: 'Sur emballage final : désignation produit, code lot, poids net, origine MDG, n° opérateur certificateur, logo Eurofeuille (sauf conversion), date limite consommation/utilisation, conditions de conservation.',
    crit: 'majeure',
    preuve: 'Spécimen étiquette validé par l\'organisme certificateur.',
    ref: 'Règlement (UE) 2018/848, Article 33 + Règlement (UE) 1169/2011 information consommateurs',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-13',
    cat: 'gestion_post_recolte',
    titre: 'Pertes documentées avec causes',
    desc: 'Toute perte > 5% sur une étape (séchage, tri, calibrage) doit être documentée avec cause (perte d\'eau, déchets de tri, contamination). Cohérence avec bilan matière.',
    crit: 'mineure',
    preuve: 'Champs perte_kg renseignés sur les étapes ExportTrack avec note explicative.',
    ref: 'Règlement (UE) 2018/848, Article 39',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-14',
    cat: 'gestion_post_recolte',
    titre: 'Locaux de transformation propres et entretenus',
    desc: 'Bâtiments en bon état, sols, murs, plafonds nettoyables. Plan de nettoyage périodique. Pas de présence visible de moisissures, fuites, infiltrations.',
    crit: 'majeure',
    preuve: 'Plan de nettoyage + registre des nettoyages + photos locaux.',
    ref: 'Règlement (UE) 2018/848, Annexe II Partie IV + bonnes pratiques HACCP',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-POSTREC-15',
    cat: 'gestion_post_recolte',
    titre: 'Étape post-récolte documentée pour tout lot clôturé',
    desc: 'Aucun lot ne peut être clôturé sans au moins une étape post-récolte enregistrée (séchage, tri, calibrage, fermentation selon le produit).',
    crit: 'majeure',
    preuve: 'Étapes enregistrées dans ExportTrack pour chaque lot avec dates et opérateur.',
    ref: 'Règlement (UE) 2018/848, Article 28 + 39',
    auto: 1, regle: 'ETAPE_MANQUANTE',
  },
  {
    code: 'BIO-POSTREC-16',
    cat: 'gestion_post_recolte',
    titre: 'Transport interne sans contamination croisée',
    desc: 'Véhicules ou contenants de transport interne (parcelle → unité, unité → port) propres, identifiés BIO si transport mixte, et nettoyés entre lots BIO et conventionnels.',
    crit: 'mineure',
    preuve: 'Procédure transport interne + registre nettoyage véhicules.',
    ref: 'Règlement (UE) 2018/848, Annexe III §3',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 5 : QUALITÉ & SÉCURITÉ (12 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-QUAL-01',
    cat: 'qualite_securite',
    titre: 'Analyses pesticides absence de résidus',
    desc: 'Analyses multi-résidus pesticides sur lots à l\'export. Aucune trace de pesticides interdits BIO. Tolérance LMR pesticides BIO à respecter (< 0,01 mg/kg pour la plupart des substances).',
    crit: 'majeure',
    preuve: 'Bulletin d\'analyse pesticides multi-résidus < 12 mois pour chaque lot ou campagne.',
    ref: 'Règlement (UE) 2018/848, Article 30 + Règlement (CE) 396/2005 LMR',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'BIO-QUAL-02',
    cat: 'qualite_securite',
    titre: 'Analyse aflatoxines (B1 + total) pour épices et café',
    desc: 'Pour vanille, girofle, café, cacao, poivre : analyse aflatoxines B1 et somme B1+B2+G1+G2 conforme aux LMR UE (Règlement 2023/915).',
    crit: 'majeure',
    preuve: 'Bulletin d\'analyse aflatoxines avec valeurs sous LMR (B1 ≤ 5 µg/kg, total ≤ 10 µg/kg pour la plupart des épices).',
    ref: 'Règlement (UE) 2023/915 contaminants',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'BIO-QUAL-03',
    cat: 'qualite_securite',
    titre: 'Analyse ochratoxine A pour café et épices',
    desc: 'Pour café et épices : analyse ochratoxine A conforme LMR UE (5 µg/kg café torréfié, 15 µg/kg café vert, 15 µg/kg épices selon catégorie).',
    crit: 'majeure',
    preuve: 'Bulletin OTA < 12 mois.',
    ref: 'Règlement (UE) 2023/915',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'BIO-QUAL-04',
    cat: 'qualite_securite',
    titre: 'Analyse cadmium pour cacao',
    desc: 'Pour cacao Sambirano : analyse cadmium ≤ 0,8 mg/kg (chocolat) selon Règlement (UE) 2023/915.',
    crit: 'majeure',
    preuve: 'Bulletin Cd cacao < 12 mois.',
    ref: 'Règlement (UE) 2023/915',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'BIO-QUAL-05',
    cat: 'qualite_securite',
    titre: 'Analyse plomb sur produits secs',
    desc: 'Plomb (Pb) sur épices et fruits séchés : ≤ 2 mg/kg (épices), ≤ 0,2 mg/kg (fruits séchés) selon catégorie.',
    crit: 'majeure',
    preuve: 'Bulletin Pb < 12 mois.',
    ref: 'Règlement (UE) 2023/915',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'BIO-QUAL-06',
    cat: 'qualite_securite',
    titre: 'Analyse coumarine sur cannelle (cassia limit)',
    desc: 'Si cannelle Cinnamomum cassia : taux de coumarine ≤ 50 mg/kg pour denrées prêtes à consommer (Règlement aromatisants 1334/2008).',
    crit: 'mineure',
    preuve: 'Bulletin coumarine + identification botanique de l\'espèce de cannelle.',
    ref: 'Règlement (CE) 1334/2008 aromatisants',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-QUAL-07',
    cat: 'qualite_securite',
    titre: 'Analyses microbiologiques (Salmonella absente)',
    desc: 'Pour épices et produits à risque : recherche Salmonella spp. en absence sur 25g (norme par défaut). Analyses entérobactéries pour suivi hygiène.',
    crit: 'majeure',
    preuve: 'Bulletin micro avec Salmonella absente / 25g.',
    ref: 'Règlement (CE) 2073/2005 critères microbio',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'BIO-QUAL-08',
    cat: 'qualite_securite',
    titre: 'Plan d\'analyses annuel par lot/culture',
    desc: 'Plan documenté d\'échantillonnage et d\'analyses : fréquence, paramètres testés, laboratoires accrédités, échantillonnage représentatif.',
    crit: 'mineure',
    preuve: 'Document plan d\'analyses annuel signé par Propriétaire.',
    ref: 'Règlement (UE) 2018/848, Article 38',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-QUAL-09',
    cat: 'qualite_securite',
    titre: 'Laboratoires d\'analyse accrédités ISO 17025',
    desc: 'Les analyses sont confiées à des laboratoires accrédités ISO 17025 (CTHT Tamatave, IPM Antananarivo, Eurofins, Bureau Veritas, etc.).',
    crit: 'majeure',
    preuve: 'Accréditation ISO 17025 du labo + bulletins d\'analyse mentionnant le numéro d\'accréditation.',
    ref: 'Bonnes pratiques + ISO 17025',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-QUAL-10',
    cat: 'qualite_securite',
    titre: 'Procédure en cas d\'analyse non conforme',
    desc: 'Procédure écrite : si analyse non conforme, retrait immédiat du lot du circuit BIO, enquête sur la cause, action corrective, notification à l\'organisme certificateur.',
    crit: 'majeure',
    preuve: 'Procédure écrite + registre des non-conformités traitées.',
    ref: 'Règlement (UE) 2018/848, Article 29',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-QUAL-11',
    cat: 'qualite_securite',
    titre: 'Échantillothèque conservée pour traçabilité',
    desc: 'Échantillons représentatifs de chaque lot conservés au moins 6 mois après expédition (~50g par lot dans bocaux scellés étiquetés).',
    crit: 'mineure',
    preuve: 'Procédure échantillothèque + photos local + registre échantillons.',
    ref: 'Bonnes pratiques + Règlement (UE) 2018/848 Article 39',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-QUAL-12',
    cat: 'qualite_securite',
    titre: 'Allergènes maîtrisés (étiquetage et contamination croisée)',
    desc: 'Si l\'unité manipule des allergènes (sulfites pour fruits séchés, traces de fruits à coque), procédure de contrôle contamination croisée + étiquetage conforme.',
    crit: 'majeure',
    preuve: 'Liste des allergènes manipulés + procédure de contrôle.',
    ref: 'Règlement (UE) 1169/2011 information consommateurs',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 6 : SOCIAL & TRAVAIL (8 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-SOC-01',
    cat: 'social_travail',
    titre: 'Respect du salaire minimum légal malgache',
    desc: 'Tous les travailleurs (permanents, saisonniers, journaliers) reçoivent au minimum le SMIG en vigueur à Madagascar. Bulletins de salaire ou registre de paie.',
    crit: 'majeure',
    preuve: 'Bulletins de salaire ou registre de paie + référence SMIG en vigueur.',
    ref: 'Règlement (UE) 2018/848 Article 4 §a + droit du travail malgache',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-SOC-02',
    cat: 'social_travail',
    titre: 'Aucun travail des enfants de moins de 15 ans',
    desc: 'Interdiction absolue du travail des enfants de moins de 15 ans dans toutes les opérations agricoles et post-récolte. Pour les 15-18 ans, pas de travaux dangereux.',
    crit: 'majeure',
    preuve: 'Registre du personnel avec dates de naissance. Déclaration sur l\'honneur.',
    ref: 'Convention OIT 138 + droit du travail malgache',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-SOC-03',
    cat: 'social_travail',
    titre: 'Aucun travail forcé ni servitude pour dette',
    desc: 'Aucune forme de travail forcé, contrainte, servitude pour dette, retention d\'identité ou de salaire.',
    crit: 'majeure',
    preuve: 'Contrats de travail libres + entretien aléatoire avec employés.',
    ref: 'Convention OIT 29 et 105',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-SOC-04',
    cat: 'social_travail',
    titre: 'Équipements de protection individuelle (EPI) fournis',
    desc: 'Pour opérations à risque (cuivre, soufre, manipulation produits) : gants, masques, lunettes, bottes fournis par l\'employeur. Formation à l\'usage.',
    crit: 'majeure',
    preuve: 'Registre de remise EPI + photos terrain + factures EPI.',
    ref: 'Règlement (UE) 2018/848 Article 4 + bonnes pratiques OIT',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-SOC-05',
    cat: 'social_travail',
    titre: 'Accès eau potable et installations sanitaires',
    desc: 'Travailleurs ont accès à eau potable, toilettes, et zone de repos sur lieux de travail. Éloignement raisonnable.',
    crit: 'mineure',
    preuve: 'Photos installations + plan d\'aménagement.',
    ref: 'Règlement (UE) 2018/848 Article 4 + Convention OIT 184',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-SOC-06',
    cat: 'social_travail',
    titre: 'Liberté syndicale et négociation collective',
    desc: 'Liberté de constitution et d\'adhésion à un syndicat. Aucune sanction pour activité syndicale légitime.',
    crit: 'majeure',
    preuve: 'Charte interne respect liberté syndicale + absence de litige.',
    ref: 'Convention OIT 87 et 98',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-SOC-07',
    cat: 'social_travail',
    titre: 'Aucune discrimination',
    desc: 'Pas de discrimination à l\'embauche ni dans les conditions de travail (genre, ethnie, religion, orientation, situation familiale).',
    crit: 'majeure',
    preuve: 'Charte interne anti-discrimination + statistiques effectifs (genre, origine).',
    ref: 'Convention OIT 100 et 111',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-SOC-08',
    cat: 'social_travail',
    titre: 'Heures de travail conformes au code du travail',
    desc: 'Durée légale de travail respectée (40-48h/semaine selon convention). Heures supplémentaires majorées et limitées.',
    crit: 'mineure',
    preuve: 'Registre des heures de travail + bulletins de paie cohérents.',
    ref: 'Code du travail malgache',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 7 : GOUVERNANCE (6 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-GOUV-01',
    cat: 'gouvernance',
    titre: 'Notification d\'activité auprès organisme certificateur',
    desc: 'Notification écrite de l\'activité BIO auprès de l\'organisme certificateur choisi (Ecocert, ControlUnion, BCS) avec dossier de demande de certification complet.',
    crit: 'majeure',
    preuve: 'Copie de la notification + accusé de réception de l\'organisme certificateur.',
    ref: 'Règlement (UE) 2018/848, Article 34',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-GOUV-02',
    cat: 'gouvernance',
    titre: 'Contrat de certification signé et à jour',
    desc: 'Contrat tripartite signé entre l\'opérateur et l\'organisme certificateur, mentionnant le périmètre certifié, la durée, les obligations.',
    crit: 'majeure',
    preuve: 'Copie du contrat signé en cours de validité.',
    ref: 'Règlement (UE) 2018/848, Article 38',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-GOUV-03',
    cat: 'gouvernance',
    titre: 'Audit annuel de l\'organisme certificateur passé',
    desc: 'Audit physique annuel réalisé par l\'organisme certificateur. Suivi des recommandations et levée des non-conformités dans les délais.',
    crit: 'majeure',
    preuve: 'Rapport d\'audit annuel + plan d\'actions correctives + preuves de levée.',
    ref: 'Règlement (UE) 2018/848, Article 38',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-GOUV-04',
    cat: 'gouvernance',
    titre: 'Notification des changements significatifs',
    desc: 'Toute modification importante (nouvelle parcelle, nouvelle unité, nouveau produit, nouvel intrant, changement procédé) notifiée à l\'organisme certificateur sous 30 jours.',
    crit: 'majeure',
    preuve: 'Registre des modifications + copies des notifications.',
    ref: 'Règlement (UE) 2018/848, Article 39',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-GOUV-05',
    cat: 'gouvernance',
    titre: 'Personne responsable BIO désignée',
    desc: 'Désignation formelle d\'un responsable BIO dans l\'organisation, point de contact pour l\'organisme certificateur, formé aux exigences réglementaires.',
    crit: 'mineure',
    preuve: 'Lettre de mission ou organigramme + CV/formation du responsable.',
    ref: 'Règlement (UE) 2018/848, Article 36',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-GOUV-06',
    cat: 'gouvernance',
    titre: 'Gestion des non-conformités majeures avec plan correctif',
    desc: 'Toute non-conformité majeure détectée fait l\'objet d\'une analyse de cause, plan correctif daté, suivi de mise en œuvre, validation finale par responsable BIO.',
    crit: 'majeure',
    preuve: 'Procédure écrite + registre des NC traitées avec dates et signatures.',
    ref: 'Règlement (UE) 2018/848, Article 29',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 8 : ENVIRONNEMENT (10 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-ENV-01',
    cat: 'environnement',
    titre: 'Préservation biodiversité (zones non cultivées)',
    desc: 'Maintien d\'au moins 5% de la SAU en éléments favorables à la biodiversité (haies, bosquets, mares, jachères fleuries, bandes enherbées).',
    crit: 'mineure',
    preuve: 'Plan parcellaire identifiant les zones de biodiversité + photos.',
    ref: 'Règlement (UE) 2018/848, Article 6 §b',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-ENV-02',
    cat: 'environnement',
    titre: 'Aucune déforestation après date de référence',
    desc: 'Aucune conversion de forêt ou écosystème naturel en parcelle agricole après le 1er janvier 2008 (alignement BIO/RA). Cartographie satellite recommandée.',
    crit: 'majeure',
    preuve: 'Images satellite historiques (Global Forest Watch, Sentinel-2) + déclaration sur l\'honneur.',
    ref: 'Règlement (UE) 2018/848 Article 6 + alignement Rainforest 2014',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-ENV-03',
    cat: 'environnement',
    titre: 'Gestion économe de l\'eau',
    desc: 'Pratiques économes : irrigation localisée (goutte-à-goutte), paillage pour rétention, choix de cultures adaptées. Pas de gaspillage manifeste.',
    crit: 'mineure',
    preuve: 'Description du système d\'irrigation + plan de gestion eau.',
    ref: 'Règlement (UE) 2018/848 Article 6 §c',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-ENV-04',
    cat: 'environnement',
    titre: 'Gestion des déchets agricoles',
    desc: 'Plan de tri et de gestion : compostage des déchets verts, collecte séparée des emballages d\'intrants, élimination via filière agréée pour les déchets dangereux.',
    crit: 'mineure',
    preuve: 'Plan de gestion des déchets + photos zones de tri.',
    ref: 'Règlement (UE) 2018/848 Article 6 + bonnes pratiques',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-ENV-05',
    cat: 'environnement',
    titre: 'Pas de pollution des cours d\'eau',
    desc: 'Bandes enherbées le long des cours d\'eau, pas d\'épandage à proximité des points d\'eau, pas de rejets d\'eaux usées non traitées.',
    crit: 'majeure',
    preuve: 'Plan parcellaire avec bandes tampons + photos cours d\'eau préservés.',
    ref: 'Règlement (UE) 2018/848 Article 6 + droit environnement malgache',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-ENV-06',
    cat: 'environnement',
    titre: 'Préservation espèces protégées',
    desc: 'Identification des espèces protégées (faune et flore) présentes sur l\'exploitation et mesures de préservation. Pas de capture, prélèvement, destruction.',
    crit: 'mineure',
    preuve: 'Inventaire écologique succinct + charte de préservation.',
    ref: 'Convention CITES + droit environnement malgache',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-ENV-07',
    cat: 'environnement',
    titre: 'Énergies renouvelables encouragées',
    desc: 'Utilisation d\'énergies renouvelables (solaire pour séchage, biomasse pour chauffage) encouragée. Limitation des combustibles fossiles.',
    crit: 'recommandation',
    preuve: 'Description des sources d\'énergie utilisées.',
    ref: 'Règlement (UE) 2018/848 Article 6 §c',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-ENV-08',
    cat: 'environnement',
    titre: 'Réduction des emballages plastiques',
    desc: 'Préférence pour emballages réutilisables, biodégradables ou recyclables. Tri et collecte des plastiques agricoles.',
    crit: 'mineure',
    preuve: 'Liste des emballages utilisés + filière de collecte plastiques agricoles.',
    ref: 'Règlement (UE) 2018/848 Article 6 + Directive UE 2019/904 plastiques',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-ENV-09',
    cat: 'environnement',
    titre: 'Lutte contre l\'érosion sur pentes',
    desc: 'Sur pentes (peu pertinent pour Site D bas-fond, applicable Sites A/B/C tanety), aménagements anti-érosion : courbes de niveau, banquettes, couverture permanente.',
    crit: 'mineure',
    preuve: 'Photos parcelles en pente avec aménagements visibles.',
    ref: 'Règlement (UE) 2018/848 Annexe II Partie I §1.9.1',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-ENV-10',
    cat: 'environnement',
    titre: 'Suivi de la fertilité des sols (analyses périodiques)',
    desc: 'Analyses de sol périodiques (tous les 3-5 ans) avec suivi des paramètres : MO, pH, P, K, oligo-éléments. Fertilisation adaptée aux résultats.',
    crit: 'mineure',
    preuve: 'Bulletins d\'analyse de sol + plan de fertilisation pluriannuel.',
    ref: 'Règlement (UE) 2018/848 Annexe II Partie I §1.9',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 9 : DOCUMENTATION (10 exigences)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-DOC-01',
    cat: 'documentation',
    titre: 'Manuel qualité BIO documenté',
    desc: 'Manuel décrivant les procédures internes : production, transformation, traçabilité, gestion des intrants, lutte non-conformités, formations.',
    crit: 'majeure',
    preuve: 'Manuel qualité daté, signé, version à jour disponible.',
    ref: 'Règlement (UE) 2018/848 Article 39',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-DOC-02',
    cat: 'documentation',
    titre: 'Procédures opérationnelles écrites',
    desc: 'Procédures détaillées par opération critique : récolte, séchage, tri, conditionnement, étiquetage, expédition, gestion non-conformité, rappel produit.',
    crit: 'majeure',
    preuve: 'Liste des procédures + documents disponibles.',
    ref: 'Règlement (UE) 2018/848 Article 39',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-DOC-03',
    cat: 'documentation',
    titre: 'Registre des intrants utilisés (chronologique)',
    desc: 'Registre datable mentionnant : date application, parcelle, produit, dose, quantité, opérateur. Conservé 5 ans.',
    crit: 'majeure',
    preuve: 'Registre des intrants disponible et tenu à jour.',
    ref: 'Règlement (UE) 2018/848 Article 39 §1(d)',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-DOC-04',
    cat: 'documentation',
    titre: 'Registre des opérations culturales',
    desc: 'Registre mentionnant chaque opération significative : préparation sol, semis, désherbage, taille, récolte. Date, parcelle, opérateur.',
    crit: 'mineure',
    preuve: 'Registre disponible + cohérent avec récoltes finales.',
    ref: 'Règlement (UE) 2018/848 Article 39',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-DOC-05',
    cat: 'documentation',
    titre: 'Registre des formations dispensées',
    desc: 'Registre des formations annuelles dispensées au personnel : BIO, hygiène, sécurité, EPI. Dates, contenu, signatures des participants.',
    crit: 'mineure',
    preuve: 'Registre formations + attestations signées.',
    ref: 'Règlement (UE) 2018/848 + Codex CXC 1-1969',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-DOC-06',
    cat: 'documentation',
    titre: 'Toutes exigences majeures justifiées par preuve',
    desc: 'Pour chaque exigence de criticité majeure dans cet engagement, au moins une preuve enregistrée dans CertifTrack.',
    crit: 'majeure',
    preuve: 'Vérification automatique : moteur de conformité scrute les preuves manquantes sur exigences majeures.',
    ref: 'Règlement (UE) 2018/848 Article 39 + bonnes pratiques audit',
    auto: 1, regle: 'PREUVE_MANQUANTE_MAJEURE',
  },
  {
    code: 'BIO-DOC-07',
    cat: 'documentation',
    titre: 'Plan d\'audit interne annuel',
    desc: 'Audit interne BIO réalisé annuellement par responsable interne ou consultant externe avant l\'audit officiel. Permet d\'identifier les écarts.',
    crit: 'mineure',
    preuve: 'Rapport d\'audit interne avec date, points contrôlés, écarts identifiés, plan d\'actions.',
    ref: 'Règlement (UE) 2018/848 + bonnes pratiques ISO 19011',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-DOC-08',
    cat: 'documentation',
    titre: 'Archivage sécurisé des registres',
    desc: 'Locaux d\'archivage sécurisés contre incendie, humidité, vol. Sauvegarde numérique recommandée.',
    crit: 'mineure',
    preuve: 'Description du système d\'archivage + photos local.',
    ref: 'Règlement (UE) 2018/848 Article 39',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-DOC-09',
    cat: 'documentation',
    titre: 'Cartographie GPS des parcelles maintenue à jour',
    desc: 'Coordonnées GPS de toutes les parcelles BIO mises à jour annuellement. Format compatible audit (KML, GeoJSON, ou listing GPS).',
    crit: 'mineure',
    preuve: 'Fichier KML ou listing GPS daté. Disponible via AgroMap.',
    ref: 'Règlement (UE) 2018/848 Article 39',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-DOC-10',
    cat: 'documentation',
    titre: 'Politique d\'entreprise BIO formalisée',
    desc: 'Document de politique BIO de l\'entreprise signé par direction : engagement environnemental, social, qualité. Affiché et communiqué au personnel.',
    crit: 'recommandation',
    preuve: 'Document politique BIO + affichage interne.',
    ref: 'Règlement (UE) 2018/848 + bonnes pratiques ISO 14001',
    auto: 0, regle: null,
  },

  // ════════════════════════════════════════════════════════════
  // CATÉGORIE 10 : SPÉCIFIQUE PÉRENNES (11 exigences additionnelles)
  // ════════════════════════════════════════════════════════════
  {
    code: 'BIO-PER-01',
    cat: 'pratiques_culturales',
    titre: 'Délai conversion 36 mois pour cultures pérennes',
    desc: 'Pour vanille, girofle, café, cacao, poivre, cannelle, litchi : période de conversion de 36 mois (3 ans) avant que la production puisse être commercialisée comme BIO.',
    crit: 'majeure',
    preuve: 'Date de début de conversion enregistrée + écart calculé automatiquement avec date de récolte.',
    ref: 'Règlement (UE) 2018/848, Article 10 §1 et Annexe II Partie I',
    auto: 1, regle: 'DELAI_CONVERSION_BIO',
  },
  {
    code: 'BIO-PER-02',
    cat: 'pratiques_culturales',
    titre: 'Plantation pérenne sur sol non contaminé',
    desc: 'Pour nouvelles plantations pérennes : analyse de sol initiale (Pb, Cd, As) si historique douteux. Sols dégradés à éviter.',
    crit: 'majeure',
    preuve: 'Analyse de sol initiale conservée. Photos parcelles à la plantation.',
    ref: 'Règlement (UE) 2018/848 Annexe II Partie I §1.7',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PER-03',
    cat: 'pratiques_culturales',
    titre: 'Diversification cultures associées (agroforesterie)',
    desc: 'Plantations pérennes en système agroforestier : association avec arbres fruitiers, légumineuses ligneuses, espèces indigènes pour ombrage et biodiversité.',
    crit: 'mineure',
    preuve: 'Inventaire des espèces associées par parcelle pérenne.',
    ref: 'Règlement (UE) 2018/848 Article 6 + bonnes pratiques tropicales',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PER-04',
    cat: 'pratiques_culturales',
    titre: 'Taille et entretien selon cycle physiologique',
    desc: 'Tailles raisonnées (formation, fructification, sanitaire) selon physiologie de chaque culture. Outils propres pour éviter propagation maladies.',
    crit: 'mineure',
    preuve: 'Calendrier de taille par culture + registre des opérations.',
    ref: 'Bonnes pratiques agronomiques + ITK BIO',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PER-05',
    cat: 'gestion_post_recolte',
    titre: 'Pollinisation manuelle vanille documentée',
    desc: 'Pour vanille : pollinisation manuelle (technique du « mariage ») effectuée par personnel formé, en saison adéquate (juillet-octobre selon zone). Registre de pollinisation.',
    crit: 'mineure',
    preuve: 'Registre des séances de pollinisation + nombre de fleurs pollinisées.',
    ref: 'Cahier ITK vanille MDG + Annexe II 2018/848',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PER-06',
    cat: 'gestion_post_recolte',
    titre: 'Stockage long terme épices avec contrôle température',
    desc: 'Pour vanille, girofle, cannelle, poivre stockés > 6 mois : local à T° contrôlée (15-25°C), HR 60-70% pour vanille, < 65% pour autres épices.',
    crit: 'majeure',
    preuve: 'Relevés HR/T° du local + plan d\'aménagement.',
    ref: 'Règlement (UE) 2018/848 Annexe II + bonnes pratiques épices',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PER-07',
    cat: 'qualite_securite',
    titre: 'Test vanilline pour vanille noire (≥ 1,6%)',
    desc: 'Pour vanille noire prête : taux de vanilline ≥ 1,6% sur matière sèche, mesuré en laboratoire accrédité.',
    crit: 'majeure',
    preuve: 'Bulletin d\'analyse vanilline ≥ 1,6% sur matière sèche.',
    ref: 'Cahier des charges vanille MDG + Codex épices',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'BIO-PER-08',
    cat: 'qualite_securite',
    titre: 'Test eugénol pour girofle (≥ 75%)',
    desc: 'Pour girofle qualité export : taux d\'eugénol dans l\'huile essentielle ≥ 75%, mesuré en laboratoire.',
    crit: 'mineure',
    preuve: 'Bulletin d\'analyse eugénol.',
    ref: 'Codex épices + ISO 3142 girofle',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PER-09',
    cat: 'qualite_securite',
    titre: 'Test fermentation cacao (cut-test ≥ 80% bien fermenté)',
    desc: 'Pour cacao Sambirano fin : test de coupe (cut-test) sur 100 fèves : minimum 80% bien fermenté (couleur brune avec stries violettes minimales).',
    crit: 'majeure',
    preuve: 'Bulletin cut-test signé par opérateur + photos fèves coupées.',
    ref: 'ICCO Quality Standards + Codex cacao',
    auto: 1, regle: 'ANALYSE_NON_CONFORME',
  },
  {
    code: 'BIO-PER-10',
    cat: 'qualite_securite',
    titre: 'Test SCA pour café spécialité (cupping ≥ 80 pts)',
    desc: 'Pour café Arabica spécialité : score de dégustation SCA (cupping) ≥ 80 points par dégustateur Q-Grader certifié.',
    crit: 'mineure',
    preuve: 'Bulletin de cupping SCA signé Q-Grader avec score détaillé.',
    ref: 'Specialty Coffee Association SCAA Cupping Protocol',
    auto: 0, regle: null,
  },
  {
    code: 'BIO-PER-11',
    cat: 'gestion_post_recolte',
    titre: 'Conditionnement final pérennes en double emballage',
    desc: 'Pour épices haute valeur (vanille, girofle, cannelle) : conditionnement final en double emballage (sachet plastique alimentaire + carton ou boîte) pour préservation arômes et anti-contamination.',
    crit: 'mineure',
    preuve: 'Spécimens d\'emballage + fiches techniques matériaux.',
    ref: 'Règlement (UE) 2018/848 + bonnes pratiques contact alimentaire',
    auto: 0, regle: null,
  },
];

// ============================================================
// SEED IDEMPOTENT
// ============================================================

export const seedCertifTrackBioUe = () => {
  const ref = db.getFirstSync(
    'SELECT id FROM referentiels WHERE code = ?',
    [REF_CODE]
  );
  if (!ref) {
    console.log(`⚠ Référentiel ${REF_CODE} introuvable, seed BIO UE annulé`);
    return;
  }

  // Vérifier combien d'exigences BIO UE existent déjà
  const existingCount = db.getFirstSync(
    'SELECT COUNT(*) as nb FROM exigences_referentiel WHERE referentiel_id = ?',
    [ref.id]
  );

  // Cible : 3 démo + 117 nouvelles = 120
  if (existingCount.nb >= 120) {
    console.log(`✅ Seed BIO UE déjà complet (${existingCount.nb} exigences)`);
    return;
  }

  console.log(`🌱 Seed BIO UE Session 8a — ${EXIGENCES_BIO_UE.length} exigences à insérer...`);

  let insere = 0;
  let skip = 0;
  let ordre = 100; // commence à 100 pour ne pas conflit avec démo (1-3)

  EXIGENCES_BIO_UE.forEach((ex) => {
    const existing = db.getFirstSync(
      'SELECT id FROM exigences_referentiel WHERE referentiel_id = ? AND code_exigence = ?',
      [ref.id, ex.code]
    );
    if (existing) { skip++; return; }

    db.runSync(
      `INSERT INTO exigences_referentiel (
        referentiel_id, code_exigence, categorie, titre, description,
        criticite, preuve_attendue, reference_officielle,
        auto_verifiable, regle_auto_code, ordre
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        ref.id, ex.code, ex.cat, ex.titre, ex.desc,
        ex.crit, ex.preuve, ex.ref,
        ex.auto || 0, ex.regle || null, ordre++,
      ]
    );
    insere++;
  });

  if (skip > 0) console.log(`  ↪ ${skip} exigences déjà présentes`);
  const final = db.getFirstSync(
    'SELECT COUNT(*) as nb FROM exigences_referentiel WHERE referentiel_id = ?',
    [ref.id]
  );
  console.log(`✅ Seed BIO UE complet : ${final.nb} exigences en base (${insere} nouvelles)`);
};