// Contenu agronomique de référence — cultures fourragères Hautes Terres Madagascar
// Calibré pour zone Analamanga, altitude 900-1400m

export const CULTURES_FOURRAGERES = [
  // ═══ GRAMINÉES ═══
  {
    code: 'brachiaria_brizantha',
    nom_fr: 'Brachiaria brizantha',
    nom_local: 'Braky',
    nom_scientifique: 'Urochloa brizantha',
    famille: 'Poaceae',
    type: 'fourrage_graminee',
    cycle_jours: 60,         // première coupe
    zones_adaptees: ['hautes_terres', 'moyen_ouest'],
    altitude_min: 600, altitude_max: 1600,
    temp_min: 15, temp_max: 35,
    pluvio_min: 800, pluvio_optimale: 1200,
    tolerance_secheresse: 'bonne',
    type_sol_prefere: 'limoneux à argileux, pH 5-7',
    notes: 'Espèce principale pâturage et affouragement. Rendement 15-20 t MS/ha/an. Repousse rapide après coupe.',
  },
  {
    code: 'bana_grass',
    nom_fr: 'Bana grass',
    nom_local: 'Bana',
    nom_scientifique: 'Pennisetum purpureum × P. americanum',
    famille: 'Poaceae',
    type: 'fourrage_graminee',
    cycle_jours: 45,
    zones_adaptees: ['hautes_terres', 'cote_est', 'nord'],
    altitude_min: 0, altitude_max: 1600,
    temp_min: 18, temp_max: 38,
    pluvio_min: 1000, pluvio_optimale: 1500,
    tolerance_secheresse: 'moyenne',
    type_sol_prefere: 'tous types, préfère limoneux fertile',
    notes: 'Très haute productivité (30-40 t MS/ha/an). Coupe tous les 45-60 jours. Idéal affouragement en vert. Sensible au gel.',
  },
  {
    code: 'juncao',
    nom_fr: 'Juncao',
    nom_local: 'Juncao',
    nom_scientifique: 'Pennisetum hydridum',
    famille: 'Poaceae',
    type: 'fourrage_graminee',
    cycle_jours: 50,
    zones_adaptees: ['hautes_terres'],
    altitude_min: 800, altitude_max: 1800,
    temp_min: 12, temp_max: 32,
    pluvio_min: 900, pluvio_optimale: 1300,
    tolerance_secheresse: 'moyenne',
    type_sol_prefere: 'limoneux, pH 5.5-7',
    notes: 'Adapté aux altitudes > 1000m. Double usage fourrage+champignons. Tolérance relative au froid.',
  },
  {
    code: 'sorgho_fourrager',
    nom_fr: 'Sorgho fourrager',
    nom_local: 'Joba',
    nom_scientifique: 'Sorghum bicolor',
    famille: 'Poaceae',
    type: 'fourrage_graminee',
    cycle_jours: 90,
    zones_adaptees: ['hautes_terres', 'moyen_ouest', 'sud'],
    altitude_min: 400, altitude_max: 1400,
    temp_min: 18, temp_max: 40,
    pluvio_min: 500, pluvio_optimale: 900,
    tolerance_secheresse: 'excellente',
    type_sol_prefere: 'tous types, tolère argilo-limoneux',
    notes: 'Idéal saison sèche / soudure fourragère. Culture annuelle, production en 90j. Stock en fourrage sec ou ensilage.',
  },
  {
    code: 'avoine_fourragere',
    nom_fr: 'Avoine fourragère',
    nom_local: 'Avwàn',
    nom_scientifique: 'Avena sativa',
    famille: 'Poaceae',
    type: 'fourrage_graminee',
    cycle_jours: 75,
    zones_adaptees: ['hautes_terres'],
    altitude_min: 1000, altitude_max: 1800,
    temp_min: 8, temp_max: 25,
    pluvio_min: 600, pluvio_optimale: 1000,
    tolerance_secheresse: 'faible',
    type_sol_prefere: 'limoneux, bien drainé, pH 6-7.5',
    notes: 'Excellent fourrage saison fraîche (mai-sept sur Hautes Terres). Cycle court. Associer avec vesce pour améliorer valeur protéique.',
  },
  {
    code: 'chloris_gayana',
    nom_fr: 'Chloris de Rhodes',
    nom_local: 'Chloris',
    nom_scientifique: 'Chloris gayana',
    famille: 'Poaceae',
    type: 'fourrage_graminee',
    cycle_jours: 55,
    zones_adaptees: ['hautes_terres', 'moyen_ouest'],
    altitude_min: 600, altitude_max: 1500,
    temp_min: 15, temp_max: 38,
    pluvio_min: 600, pluvio_optimale: 1100,
    tolerance_secheresse: 'bonne',
    type_sol_prefere: 'sableux à limoneux, tolère pH alcalin',
    notes: 'Adapté sols pauvres et secs. Bonne valeur nutritive. Utile sur tanety dégradés.',
  },
  {
    code: 'paille_riz',
    nom_fr: 'Paille de riz',
    nom_local: 'Mololo',
    nom_scientifique: 'Oryza sativa (résidu)',
    famille: 'Poaceae',
    type: 'fourrage_graminee',
    cycle_jours: null,  // résidu de récolte, pas de cycle propre
    zones_adaptees: ['hautes_terres', 'cote_est', 'moyen_ouest'],
    altitude_min: 0, altitude_max: 1800,
    temp_min: null, temp_max: null,
    pluvio_min: null, pluvio_optimale: null,
    tolerance_secheresse: null,
    type_sol_prefere: null,
    notes: 'Résidu rizicole. Valeur nutritive faible (UF 0.3). Toujours associer à une légumineuse ou provende. Rôle de complément de volume en saison sèche.',
  },

  // ═══ LÉGUMINEUSES ARBUSTIVES ═══
  {
    code: 'sesbania_sesban',
    nom_fr: 'Sésbanie',
    nom_local: 'Sesbania',
    nom_scientifique: 'Sesbania sesban',
    famille: 'Fabaceae',
    type: 'fourrage_legumineuse',
    cycle_jours: 180,  // première taille productive
    zones_adaptees: ['hautes_terres', 'cote_est'],
    altitude_min: 800, altitude_max: 1600,
    temp_min: 15, temp_max: 35,
    pluvio_min: 800, pluvio_optimale: 1200,
    tolerance_secheresse: 'bonne',
    type_sol_prefere: 'bien drainé, tolère bas-fonds temporaires',
    notes: `Arbuste fixateur d'azote. Fourrage très riche en protéines (25-28% MS). Taille 2-3x/an. Rôle agroforestier important.`,
  },
  
  {
    code: 'tephrosia_vogelii',
    nom_fr: 'Téphrosie',
    nom_local: 'Tephrosia',
    nom_scientifique: 'Tephrosia vogelii',
    famille: 'Fabaceae',
    type: 'fourrage_legumineuse',
    cycle_jours: 150,
    zones_adaptees: ['hautes_terres'],
    altitude_min: 800, altitude_max: 1600,
    temp_min: 14, temp_max: 32,
    pluvio_min: 700, pluvio_optimale: 1100,
    tolerance_secheresse: 'bonne',
    type_sol_prefere: 'limoneux à argileux',
    notes: 'Double usage : fourrage + amendement vert. Améliore la fertilité du sol. Légèrement toxique en excès — rationnement conseillé (max 20% ration).',
  },
  {
    code: 'cajanus_cajan',
    nom_fr: `Pois d'Angole`,
    nom_local: 'Ambatry',
    nom_scientifique: 'Cajanus cajan',
    famille: 'Fabaceae',
    type: 'fourrage_legumineuse',
    cycle_jours: 120,
    zones_adaptees: ['hautes_terres', 'moyen_ouest', 'nord'],
    altitude_min: 400, altitude_max: 1500,
    temp_min: 18, temp_max: 38,
    pluvio_min: 600, pluvio_optimale: 1000,
    tolerance_secheresse: 'excellente',
    type_sol_prefere: 'tous types, excellent sur sols pauvres',
    notes: `Triple usage : fourrage feuilles, grains comestibles, bois de feu. Fixateur d'azote puissant. Dure 3-5 ans. Idéal intégration agroforestière.`,
  },

  // ═══ COUVRE-SOLS / ENGRAIS VERTS ═══
  {
    code: 'mucuna_pruriens',
    nom_fr: 'Mucuna',
    nom_local: 'Silivohitse',
    nom_scientifique: 'Mucuna pruriens',
    famille: 'Fabaceae',
    type: 'fourrage_legumineuse',
    cycle_jours: 90,
    zones_adaptees: ['hautes_terres', 'cote_est', 'moyen_ouest'],
    altitude_min: 400, altitude_max: 1400,
    temp_min: 18, temp_max: 35,
    pluvio_min: 800, pluvio_optimale: 1300,
    tolerance_secheresse: 'moyenne',
    type_sol_prefere: 'tous types, améliorateur sol',
    notes: 'Couvre-sol + engrais vert + fourrage. Graines riches protéines mais à préparer (trempage). Suppression adventices excellente. Biomasse 20-30 t/ha.',
  },
  {
    code: 'soja_fourrager',
    nom_fr: 'Soja',
    nom_local: 'Soja',
    nom_scientifique: 'Glycine max',
    famille: 'Fabaceae',
    type: 'fourrage_legumineuse',
    cycle_jours: 100,
    zones_adaptees: ['hautes_terres', 'moyen_ouest'],
    altitude_min: 800, altitude_max: 1400,
    temp_min: 18, temp_max: 32,
    pluvio_min: 700, pluvio_optimale: 1100,
    tolerance_secheresse: 'faible',
    type_sol_prefere: 'limoneux profond, pH 6-7',
    notes: 'Double usage fourrage + grains. Fanes post-récolte excellentes pour complément protéique. Inoculer avec rhizobium pour fixation azote optimale.',
  },

  // ═══ COLLECTÉ HORS SITE ═══
  {
    code: 'desmodium_intortum',
    nom_fr: 'Desmodium',
    nom_local: 'Desmodium',
    nom_scientifique: 'Desmodium intortum',
    famille: 'Fabaceae',
    type: 'fourrage_legumineuse',
    cycle_jours: 90,
    zones_adaptees: ['hautes_terres', 'cote_est'],
    altitude_min: 900, altitude_max: 1700,
    temp_min: 14, temp_max: 30,
    pluvio_min: 900, pluvio_optimale: 1400,
    tolerance_secheresse: 'faible',
    type_sol_prefere: 'limoneux, bien drainé',
    notes: 'Légumineuse rampante haute valeur nutritive (20% protéines). Pousse spontanément sur bords de route. À terme : implanter en sous-étage agroforestier.',
  },
];

export const STADES_FOURRAGERS = [
  // ─── Brachiaria brizantha ───
  { culture_code: 'brachiaria_brizantha', ordre: 1, code: 'semis',       nom_fr: 'Semis / bouturage',      jour_debut: 0,  jour_fin: 3,   description: 'Mise en place — boutures 30cm enfouies aux 2/3', action_recommandee: 'Arroser immédiatement après mise en place. Sol humide obligatoire.' },
  { culture_code: 'brachiaria_brizantha', ordre: 2, code: 'levee',       nom_fr: 'Levée',                   jour_debut: 10, jour_fin: 18,  description: 'Apparition des premières feuilles', action_recommandee: 'Observer densité levée. Si < 70%, ressemer les manques.' },
  { culture_code: 'brachiaria_brizantha', ordre: 3, code: 'tallage',     nom_fr: 'Tallage actif',           jour_debut: 20, jour_fin: 35,  description: 'Multiplication des tiges depuis la souche', action_recommandee: 'Apport fumure organique si disponible. Désherbage si couverture adventices > 30%.' },
  { culture_code: 'brachiaria_brizantha', ordre: 4, code: 'floraison',   nom_fr: 'Floraison',               jour_debut: 45, jour_fin: 55,  description: 'Apparition des épillets, pollinisation', action_recommandee: 'Si coupe pour fourrage : couper AVANT floraison complète (J+40-45) pour maximiser valeur nutritive.' },
  { culture_code: 'brachiaria_brizantha', ordre: 5, code: 'coupe_1',     nom_fr: '1ère coupe',              jour_debut: 50, jour_fin: 65,  description: 'Première récolte. Couper à 15-20cm du sol.', action_recommandee: 'Hauteur de coupe : 15-20cm. Laisser repousser 30-35 jours entre coupes.' },
  { culture_code: 'brachiaria_brizantha', ordre: 6, code: 'repousse',    nom_fr: 'Repousse post-coupe',     jour_debut: 65, jour_fin: 90,  description: 'Régénération après coupe', action_recommandee: 'Apport fumure organique pour stimuler repousse. Arrosage si saison sèche.' },

  // ─── Bana grass ───
  { culture_code: 'bana_grass', ordre: 1, code: 'plantation',   nom_fr: 'Plantation',             jour_debut: 0,  jour_fin: 5,   description: 'Éclats de souche ou boutures', action_recommandee: 'Espace 1m × 0.5m. Sol bien préparé et humide. 1 bouture par poquet.' },
  { culture_code: 'bana_grass', ordre: 2, code: 'levee',        nom_fr: 'Reprise végétative',     jour_debut: 8,  jour_fin: 15,  description: 'Premières feuilles et développement racinaire', action_recommandee: 'Arrosage régulier les 15 premiers jours. Critique pour la prise.' },
  { culture_code: 'bana_grass', ordre: 3, code: 'tallage',      nom_fr: 'Tallage',                jour_debut: 20, jour_fin: 35,  description: 'Multiplication des talles', action_recommandee: 'Fertilisation organique recommandée à J+21.' },
  { culture_code: 'bana_grass', ordre: 4, code: 'coupe_1',      nom_fr: '1ère coupe',             jour_debut: 45, jour_fin: 60,  description: 'À 1m-1.2m de hauteur, couper à 20cm', action_recommandee: 'Couper quand hauteur 1-1.2m. Ne pas laisser monter à graine (perd valeur nutritive).' },
  { culture_code: 'bana_grass', ordre: 5, code: 'repousse',     nom_fr: 'Cycle de repousse',      jour_debut: 60, jour_fin: 90,  description: 'Coupe toutes les 40-50 jours ensuite', action_recommandee: 'Rythme de coupe : 40-50 jours. Apport fumure après chaque coupe.' },

  // ─── Sorgho fourrager (culture anti-soudure) ───
  { culture_code: 'sorgho_fourrager', ordre: 1, code: 'semis',       nom_fr: 'Semis',               jour_debut: 0,  jour_fin: 3,   description: 'Semis en ligne, 3-5cm profondeur', action_recommandee: 'Densité : 15kg graines/ha. Lignes espacées 50-60cm. Sol humide.' },
  { culture_code: 'sorgho_fourrager', ordre: 2, code: 'levee',       nom_fr: 'Levée',               jour_debut: 5,  jour_fin: 10,  description: 'Émergence plantules', action_recommandee: 'Démariage à 15cm entre plants si densité excessive.' },
  { culture_code: 'sorgho_fourrager', ordre: 3, code: 'montaison',   nom_fr: 'Montaison',           jour_debut: 30, jour_fin: 50,  description: 'Élongation rapide de la tige', action_recommandee: 'Fertilisation azotée si disponible. Irrigation si sécheresse prolongée.' },
  { culture_code: 'sorgho_fourrager', ordre: 4, code: 'epiaison',    nom_fr: 'Épiaison',            jour_debut: 60, jour_fin: 75,  description: 'Apparition des panicules', action_recommandee: 'Couper au stade pâteux (J+75-85) pour ensilage. Laisser mûrir pour grains secs.' },
  { culture_code: 'sorgho_fourrager', ordre: 5, code: 'recolte',     nom_fr: 'Récolte',             jour_debut: 85, jour_fin: 95,  description: 'Récolte fourrage ou grains', action_recommandee: `Pour fourrage sec : laisser sécher 7-10 jours après coupe. Stocker à l'abri.`},
];